class CfgExileCustomCode 
{
	// Trader Plus
	ExileClient_gui_traderDialog_show = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_show.sqf";
	ExileClient_gui_traderDialog_updateItemStats = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_updateItemStats.sqf";
	ExileClient_gui_vehicleTraderDialog_show = "Client\TraderPlus\CustomCode\ExileClient_gui_vehicleTraderDialog_show.sqf";
	ExileClient_gui_traderDialog_event_onStoreDropDownSelectionChanged = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_event_onStoreDropDownSelectionChanged.sqf";
	ExileClient_gui_vehicleTraderDialog_updateVehicleListBox = "Client\TraderPlus\CustomCode\ExileClient_gui_vehicleTraderDialog_updateVehicleListBox.sqf";
	ExileClient_gui_traderDialog_updateStoreListBox = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_updateStoreListBox.sqf";
	ExileClient_gui_traderDialog_event_onStoreListBoxSelectionChanged = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_event_onStoreListBoxSelectionChanged.sqf";
	ExileClient_gui_traderDialog_event_onPurchaseButtonClick = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_event_onPurchaseButtonClick.sqf";
	ExileClient_gui_traderDialog_event_onUnload = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_event_onUnload.sqf";
	ExileClient_gui_traderDialog_event_onFilterCheckboxStateChanged = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_event_onFilterCheckboxStateChanged.sqf";
	ExileClient_system_trading_network_purchaseItemResponse = "Client\TraderPlus\CustomCode\ExileClient_system_trading_network_purchaseItemResponse.sqf";
	ExileClient_gui_traderDialog_updateInventoryListBox = "Client\TraderPlus\CustomCode\ExileClient_gui_traderDialog_updateInventoryListBox.sqf";
	
	// Spawn Loadout
	ExileServer_object_player_network_createPlayerRequest = "Client\SpawnLoadout\CustomCode\ExileServer_object_player_network_createPlayerRequest.sqf";
	ExileServer_object_player_createBambi = "Client\SpawnLoadout\CustomCode\ExileServer_object_player_createBambi.sqf";
	
	// Enigma
	ExileClient_object_player_death_startBleedingOut = "Client\Enigma\CustomCode\ExileClient_object_player_death_startBleedingOut.sqf";
	ExileClient_object_player_event_onInventoryOpened = "Client\Enigma\CustomCode\ExileClient_object_player_event_onInventoryOpened.sqf";
};