class CfgExileCustomCode 
{
	ExileClient_gui_traderDialog_show = "ExileServerOverrides\ExileClient_gui_traderDialog_show.sqf";
	ExileClient_gui_traderDialog_updateItemStats = "ExileServerOverrides\ExileClient_gui_traderDialog_updateItemStats.sqf";
	ExileClient_gui_vehicleTraderDialog_show = "ExileServerOverrides\ExileClient_gui_vehicleTraderDialog_show.sqf";
	ExileClient_gui_traderDialog_event_onStoreDropDownSelectionChanged = "ExileServerOverrides\ExileClient_gui_traderDialog_event_onStoreDropDownSelectionChanged.sqf";
	ExileClient_gui_vehicleTraderDialog_updateVehicleListBox = "ExileServerOverrides\ExileClient_gui_vehicleTraderDialog_updateVehicleListBox.sqf";
	ExileClient_gui_traderDialog_updateStoreListBox = "ExileServerOverrides\ExileClient_gui_traderDialog_updateStoreListBox.sqf";
	ExileClient_gui_traderDialog_event_onStoreListBoxSelectionChanged = "ExileServerOverrides\ExileClient_gui_traderDialog_event_onStoreListBoxSelectionChanged.sqf";
	ExileClient_gui_traderDialog_event_onPurchaseButtonClick = "ExileServerOverrides\ExileClient_gui_traderDialog_event_onPurchaseButtonClick.sqf";
	ExileClient_gui_traderDialog_event_onUnload = "ExileServerOverrides\ExileClient_gui_traderDialog_event_onUnload.sqf";
	ExileClient_gui_traderDialog_event_onFilterCheckboxStateChanged = "ExileServerOverrides\ExileClient_gui_traderDialog_event_onFilterCheckboxStateChanged.sqf";
	ExileClient_system_trading_network_purchaseItemResponse = "ExileServerOverrides\ExileClient_system_trading_network_purchaseItemResponse.sqf";
	ExileClient_gui_traderDialog_updateInventoryListBox = "ExileServerOverrides\ExileClient_gui_traderDialog_updateInventoryListBox.sqf";
	ExileServer_object_player_network_createPlayerRequest = "ExileServerOverrides\ExileServer_object_player_network_createPlayerRequest.sqf";
	ExileServer_object_player_createBambi = "ExileServerOverrides\ExileServer_object_player_createBambi.sqf";
	ExileClient_object_player_death_startBleedingOut = "ExileServerOverrides\ExileClient_object_player_death_startBleedingOut.sqf";
	ExileClient_object_player_event_onInventoryOpened = "ExileServerOverrides\ExileClient_object_player_event_onInventoryOpened.sqf";
};