class CfgTraderCategories
{

	class Template
	{
		name = "Name Here";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] =
		{
			// Add your items here <3
		};
	};
	
	// Civilian
	
	class CivilianPistols
	{
		name = "Civilian Pistols";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] =
		{
			"Exile_Weapon_SA61",
			"rhs_weap_pya",
			"rhs_weap_makarov_pmm",
			"rhsusf_weap_m1911a1",
			"Exile_Weapon_Taurus",
			"BWA3_P8",
			"rhsusf_weap_glock17g4",
			"rhs_weap_savz61_folded",
			"CSW_FN57",
			"CSW_M500",
			"CSW_M26C",
			"CSW_Desert_Eagle"
			
			
		};
	};

	class CivilianRifles	
	{
		name = "Civilian Grade Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] =
		{
			"Exile_Weapon_LeeEnfield",
			"hlc_rifle_M1903A1",
			"rhs_weap_kar98k",
			"rhs_weap_akm",
			"Exile_Weapon_M16A4",
			"Exile_Weapon_M16A2",
			"Exile_Weapon_M4",
			"arifle_AKM_F",
			"arifle_AKM_FL_F",
			"Exile_Weapon_AK47",
			"arifle_AKS_F",
			"hlc_rifle_ak47",
			"hlc_rifle_akm",
			"hlc_rifle_akm_MTK",
			"hlc_rifle_aks74",
			"hlc_rifle_aks74_GL",
			"hlc_rifle_aks74_MTK",
			"hlc_rifle_aks74u",
			"hlc_rifle_aks74u_MTK",
			"rhs_weap_m16a4",
			"rhs_weap_m16a4_carryhandle",
			"rhs_weap_m16a4_carryhandle_pmag",
			"rhs_weap_akm",
			"rhs_weap_akm_gp25",
			"rhs_weap_akms_gp25",
			"hlc_rifle_M14",
			"rhs_weap_m70ab2_fold",
			"rhs_weap_m70b1",
			"rhs_weap_m70b1n",
			"rhs_weap_m70b3n",
			"rhs_weap_m70b3n_pbg40",
			"rhs_weap_m92",
			"rhs_weap_m92_fold",
			"rhs_weap_m76",
			"rhs_weap_m21a",
			"rhs_weap_m21a_pr",
			"rhs_weap_m21a_pr_pbg40",
			"rhs_weap_m21a_fold",
			"rhs_weap_m21a_pbg40",
			"rhs_weap_m21s",
			"rhs_weap_m21s_pr",
			"rhs_weap_m21s_fold",
			"rhs_weap_m82a1",
			"rhs_weap_minimi_para_railed",
			"rhs_weap_g36c",
			"rhs_weap_g36kv",
			"rhs_weap_g36kv_ag36",
			"rhs_weap_m84",
			"CUP_arifle_CZ805_A2",
            "CUP_arifle_Sa58P",
            "CUP_arifle_Sa58V",
			"CUP_srifle_CZ550"
		};
	};
	
	class Smokes
	{
		name = "Smokes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"SmokeShell",
			"SmokeShellBlue",
			"SmokeShellGreen",
			"SmokeShellOrange",
			"SmokeShellPurple",
			"SmokeShellRed",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell"
		};
	};

	class Flares
	{
		name = "Flares";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"ACE_Chemlight_HiOrange",
			"ACE_Chemlight_HiRed",
			"ACE_Chemlight_HiYellow",
			"ACE_Chemlight_HiWhite",
			"ACE_Chemlight_Orange",
			"ACE_Chemlight_White",
			"ACE_Chemlight_IR",
			"ACE_HandFlare_White",
			"ACE_HandFlare_Red",
			"ACE_HandFlare_Green",
			"ACE_HandFlare_Yellow",
			"RHS_weap_rsp30_white",
			"RHS_weap_rsp30_green",
			"RHS_weap_rsp30_red"
		};
	};
	
	class Medical
	{
		name = "Medical Equipment";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			// "ACE_personalAidKit",
			"ACE_morphine",
			"ACE_fieldDressing",
			"ACE_tourniquet",
			"ACE_bloodIV_250"
		};
	};
	
	class Hardware
	{
		name = "Hardware";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{

			"Exile_Item_DuctTape",
			"Exile_Item_ExtensionCord",
			"Exile_Item_FuelCanisterEmpty",
			"Exile_Item_JunkMetal",
			"Exile_Item_LightBulb",
			"Exile_Item_MetalBoard",
			"Exile_Item_MetalPole",
			"Exile_Item_SafeKit",
			"Exile_Item_CamoTentKit",
			"Exile_Item_CodeLock",
			"Exile_Item_MetalScrews",
			"Exile_Item_MetalWire",
			"Exile_Item_Laptop",
			"Exile_Item_BaseCameraKit",
			"Exile_Item_MetalHedgehogKit",
			"Exile_Item_Cement",
			"Exile_Item_Sand",
			"Exile_Item_MobilePhone",
			"Exile_Item_CordlessScrewdriver",
			"Exile_Item_FireExtinguisher",
			"Exile_Item_OilCanister",
			"Exile_Item_Hammer",
			"Exile_Item_Carwheel",
			"Exile_Item_SleepingMat",
			"Exile_Item_Defibrillator",
			"Exile_Item_Wrench",
			"Exile_Item_Rope",
			"Exile_Item_Matches",
			"Exile_Item_CookingPot",
			"Exile_Item_CanOpener",
			"Exile_Item_Handsaw",
			"Exile_Item_Pliers",
			"Exile_Item_Grinder",
			"Exile_Item_Foolbox",
			"Exile_Item_Screwdriver",
			"Exile_Item_Shovel",
			"Exile_Item_ToiletPaper",
			"Exile_Item_BurlapSack"
		};
	};

	class Food
	{
		name = "Fast Food";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_EMRE",
			"Exile_Item_GloriousKnakworst",
			"Exile_Item_Surstromming",
			"Exile_Item_SausageGravy",
			"Exile_Item_Catfood",
			"Exile_Item_ChristmasTinner",
			"Exile_Item_BBQSandwich",
			"Exile_Item_MacasCheese",
			"Exile_Item_Dogfood",
			"Exile_Item_BeefParts",
			"Exile_Item_Cheathas",
			"Exile_Item_Noodles",
			"Exile_Item_SeedAstics",
			"Exile_Item_Raisins",
			"Exile_Item_Moobar",
			"Exile_Item_InstantCoffee"
			
			// Hunted Animals
			// Note: Adding these to the trader will defeat the purpose of hunting!
			/*
			"Exile_Item_SheepSteak_Cooked",
			"Exile_Item_AlsatianSteak_Cooked",
			"Exile_Item_CatSharkFilet_Cooked",
			"Exile_Item_FinSteak_Cooked",
			"Exile_Item_GoatSteak_Cooked",
			"Exile_Item_TurtleFilet_Cooked",
			"Exile_Item_TunaFilet_Cooked",
			"Exile_Item_RabbitSteak_Cooked",
			"Exile_Item_ChickenFilet_Cooked",
			"Exile_Item_RoosterFilet_Cooked",
			"Exile_Item_MulletFilet_Cooked",
			"Exile_Item_SalemaFilet_Cooked",
			"Exile_Item_MackerelFilet_Cooked",
			"Exile_Item_OrnateFilet_Cooked",
			"Exile_Item_SnakeFilet_Cooked",
			"Exile_Item_CatSharkFilet_Raw",
			"Exile_Item_TunaFilet_Raw",
			"Exile_Item_AlsatianSteak_Raw",
			"Exile_Item_TurtleFilet_Raw",
			"Exile_Item_SheepSteak_Raw",
			"Exile_Item_FinSteak_Raw",
			"Exile_Item_GoatSteak_Raw",
			"Exile_Item_ChickenFilet_Raw",
			"Exile_Item_RoosterFilet_Raw",
			"Exile_Item_MackerelFilet_Raw",
			"Exile_Item_MulletFilet_Raw",
			"Exile_Item_OrnateFilet_Raw",
			"Exile_Item_RabbitSteak_Raw",
			"Exile_Item_SalemaFilet_Raw",
			"Exile_Item_SnakeFilet_Raw"
			*/
		};
	};
	
	class NonVeganFood
	{
		name = "Non-Vegan Food";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_CatSharkFilet_Raw",
			"Exile_Item_TunaFilet_Raw",
			"Exile_Item_AlsatianSteak_Raw",
			"Exile_Item_TurtleFilet_Raw",
			"Exile_Item_SheepSteak_Raw",
			"Exile_Item_FinSteak_Raw",
			"Exile_Item_GoatSteak_Raw",
			"Exile_Item_ChickenFilet_Raw",
			"Exile_Item_RoosterFilet_Raw",
			"Exile_Item_MackerelFilet_Raw",
			"Exile_Item_MulletFilet_Raw",
			"Exile_Item_OrnateFilet_Raw",
			"Exile_Item_RabbitSteak_Raw",
			"Exile_Item_SalemaFilet_Raw",
			"Exile_Item_SnakeFilet_Raw"
		};
	};
	
	class Drinks
	{
		name = "Drinks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Item_PlasticBottleCoffee",
			"Exile_Item_PowerDrink",
			"Exile_Item_PlasticBottleFreshWater",
			"Exile_Item_Beer",
			"Exile_Item_EnergyDrink",
			"Exile_Item_ChocolateMilk",
			"Exile_Item_MountainDupe",
			"Exile_Item_PlasticBottleEmpty"
		};
	};

	class Equipment
	{
		name = "Equipment";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"ACE_MapTools",
			"ACE_Flashlight_MX991",
			"ACE_Flashlight_XL50",
			"ACE_VectorDay",
			"ACE_SpottingScope",
			"ACE_Tripod",
			"ACE_NVG_Gen1",
			"ACE_NVG_Gen2",
			"ACE_Altimeter",
			"ACE_microDAGR",
			"ItemMap",
			"ItemCompass",
			"ACE_RangeCard",
			"ItemWatch",
			"Exile_Item_XM8",
			"ACE_CableTie"
		};
	};
	
	class CivilianAntiRadiationGear
	{
		name = "Anti-Radiation Gear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"skn_m04_gas_mask_bare_dry",
			"skn_m04_gas_mask_blk",
			"skn_m04_gas_mask_blu",
			"skn_m04_gas_mask_gre",
			"skn_m50_gas_mask_hood",
			"skn_u_nbc_indep_blk",
			"skn_u_nbc_bluf_mtp"
		};
	};

	class CivilianFacewear
	{
		name = "Facegear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] = 
		{
			//Glasses
			"TRYK_US_ESS_Glasses",
			"TRYK_US_ESS_Glasses_WH",
			"TRYK_US_ESS_Glasses_BLK",
			"TRYK_US_ESS_Glasses_TAN",
			"TRYK_US_ESS_Glasses_TAN_BLK",
			"TRYK_SPGEAR_Glasses",
			"TRYK_headset_Glasses",
			"TRYK_SpsetG_Glasses",
			"TRYK_Spset_PHC1_Glasses",
			"TRYK_Spset_PHC2_Glasses",
			"TRYK_US_ESS_Glasses_H",
			"TRYK_US_ESS_Glasses_Cover",
			"TRYK_headset_glasses",
			"TRYK_headset2_glasses",
			//NeckGear
			"TRYK_Shemagh_shade_MESH",
			"TRYK_Shemagh_shade_N",
			"TRYK_Shemagh_shade_G_N",
			"TRYK_Shemagh_shade_WH_N",
			"TRYK_kio_balaclava_WH",
			"TRYK_kio_balaclava_BLK",
			"TRYK_kio_balaclavas",
			"TRYK_kio_balaclava_BLK_ear",
			"TRYK_kio_balaclava_ear",
			"TRYK_kio_balaclava_ESS",
			"TRYK_Shemagh",
			"TRYK_Shemagh_mesh",
			"TRYK_Shemagh_G",
			"TRYK_Shemagh_WH",
			"TRYK_Shemagh_shade",
			"TRYK_Shemagh_shade_G",
			"TRYK_Shemagh_shade_WH",
			"TRYK_Shemagh_shade_MH",
			"TRYK_Shemagh_ESS",
			"TRYK_Shemagh_ESS_G",
			"TRYK_Shemagh_ESS_WH",
			"TRYK_Shemagh_EAR_TAN",
			"TRYK_Shemagh_EAR_TAN",
			"TRYK_Shemagh_EAR_WH",
			
			//Face Items
			"TRYK_Beard",
			"TRYK_Beard_BW",
			"TRYK_Beard_BK",
			"TRYK_Beard_Gr",
			"TRYK_Beard2",
			"TRYK_Beard_BW2",
			"TRYK_Beard_BK2",
			"TRYK_Beard_Gr2",
			"TRYK_Beard3",
			"TRYK_Beard_BW3",
			"TRYK_Beard_BK3",
			"TRYK_Beard_Gr3",
			"TRYK_Beard4",
			"TRYK_Beard_BW4",
			"TRYK_Beard_BK4",
			"TRYK_Beard_Gr4",
			"rhs_googles_black",
			"rhs_googles_clear",
			"rhs_googles_yellow",
			"rhs_googles_orange"
		};
	};

	class CivilianHeadwear
	{
		name = "Headwear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] = 
		{
			//HeadGear
			"TRYK_ESS_CAP_OD",
			"TRYK_ESS_CAP_tan",
			"TRYK_R_CAP_BLK",
			"TRYK_R_CAP_TAN",
			"TRYK_R_CAP_OD_US",
			"TRYK_r_cap_tan_Glasses",
			"TRYK_r_cap_blk_Glasses",
			"TRYK_r_cap_od_Glasses",
			"TRYK_H_headsetcap_Glasses",
			"TRYK_H_headsetcap_blk_Glasses",
			"TRYK_H_headsetcap_od_Glasses",
			"TRYK_TAC_EARMUFF_SHADE",
			"TRYK_TAC_EARMUFF",
			"TRYK_NOMIC_TAC_EARMUFF",
			"TRYK_headset2",
			"TRYK_TAC_EARMUFF_Gs",
			"TRYK_TAC_SET_bn",
			"TRYK_NOMIC_TAC_EARMUFF_Gs",
			"TRYK_TAC_EARMUFF_SHADE_Gs",
			"TRYK_TAC_SET_TAN",
			"TRYK_TAC_SET_OD",
			"TRYK_TAC_SET_WH",
			"TRYK_TAC_SET_MESH",
			"TRYK_TAC_SET_TAN_2",
			"TRYK_TAC_SET_OD_2",
			"TRYK_TAC_SET_WH_2",
			"TRYK_TAC_SET_MESH_2",
			"TRYK_bandana_g",
			"TRYK_H_PASGT_BLK",
			"TRYK_H_PASGT_OD",
			"TRYK_H_PASGT_COYO",
			"TRYK_H_PASGT_TAN",
			"TRYK_H_Helmet_Snow",
			"TRYK_H_WH",
			"TRYK_H_GR",
			"TRYK_H_AOR1",
			"TRYK_H_AOR2",
			"TRYK_H_EARMUFF",
			"TRYK_H_TACEARMUFF_H",
			"TRYK_H_Bandana_H",
			"TRYK_H_Bandana_wig",
			"TRYK_H_Bandana_wig_g",
			"TRYK_H_wig",
			"TRYK_H_headset2",
			"TRYK_H_ghillie_over",
			"TRYK_H_ghillie_top",
			"TRYK_H_ghillie_top_headless",
			"TRYK_H_ghillie_over_green",
			"TRYK_H_ghillie_top_green",
			"TRYK_H_ghillie_top_headless_green",
			"TRYK_H_woolhat",
			"TRYK_H_woolhat_CW",
			"TRYK_H_woolhat_WH",
			"TRYK_H_woolhat_br",
			"TRYK_H_woolhat_cu",
			"TRYK_H_woolhat_tan",
			"TRYK_H_headsetcap",
			"TRYK_H_headsetcap_blk",
			"TRYK_H_headsetcap_od",
			"TRYK_H_pakol",
			"TRYK_H_pakol2",
			"TRYK_H_LHS_HEL_G",
			"TRYK_H_Helmet_Winter",
			"TRYK_H_Helmet_Winter_2",
			"rhssaf_helmet_m59_85_nocamo",
			"rhssaf_helmet_m59_85_oakleaf",
			"rhssaf_helmet_m97_olive_nocamo",
			"rhssaf_helmet_m97_olive_nocamo_black_ess",
			"rhssaf_helmet_m97_olive_nocamo_black_ess_bare",
			"rhssaf_helmet_m97_black_nocamo",
			"rhssaf_helmet_m97_black_nocamo_black_ess",
			"rhssaf_helmet_m97_black_nocamo_black_ess_bare",
			"rhssaf_Helmet_m97_woodland",
			"rhssaf_Helmet_m97_digital",
			"rhssaf_Helmet_m97_md2camo",
			"rhssaf_Helmet_m97_oakleaf",
			"rhssaf_helmet_m97_nostrap_blue",
			"rhssaf_helmet_m97_nostrap_blue_tan_ess",
			"rhssaf_helmet_m97_nostrap_blue_tan_ess_bare",
			"rhssaf_helmet_m97_woodland_black_ess",
			"rhssaf_helmet_m97_woodland_black_ess_bare",
			"rhssaf_helmet_m97_digital_black_ess",
			"rhssaf_helmet_m97_digital_black_ess_bare",
			"rhssaf_helmet_m97_md2camo_black_ess",
			"rhssaf_helmet_m97_md2camo_black_ess_bare",
			"rhssaf_helmet_m97_oakleaf_black_ess",
			"rhssaf_helmet_m97_oakleaf_black_ess_bare",
			"rhssaf_helmet_hgu56p",
			"rhssaf_beret_green",
			"rhssaf_beret_red",
			"rhssaf_beret_black",
			"rhssaf_beret_blue_un",
			"rhssaf_booniehat_digital",
			"rhssaf_booniehat_md2camo",
			"rhssaf_booniehat_woodland",
			"CUP_H_C_Beanie_01",
			"CUP_H_C_Beanie_02",
			"CUP_H_C_Beanie_03",
			"CUP_H_C_Beanie_04",
			"CUP_H_TKI_Lungee_01",
			"CUP_H_TKI_Lungee_02",
			"CUP_H_TKI_Lungee_03",
			"CUP_H_TKI_Lungee_04",
			"CUP_H_TKI_Lungee_05",
			"CUP_H_TKI_Lungee_06",
			"CUP_H_TKI_Lungee_Open_01",
			"CUP_H_TKI_Lungee_Open_02",
			"CUP_H_TKI_Lungee_Open_03",
			"CUP_H_TKI_Lungee_Open_04",
			"CUP_H_TKI_Lungee_Open_05",
			"CUP_H_TKI_Lungee_Open_06",
			"CUP_H_TKI_Pakol_1_01",
			"CUP_H_TKI_Pakol_1_02",
			"CUP_H_TKI_Pakol_1_03",
			"CUP_H_TKI_Pakol_1_04",
			"CUP_H_TKI_Pakol_1_05",
			"CUP_H_TKI_Pakol_1_06",
			"CUP_H_TKI_Pakol_2_01",
			"CUP_H_TKI_Pakol_2_02",
			"CUP_H_TKI_Pakol_2_03",
			"CUP_H_TKI_Pakol_2_04",
			"CUP_H_TKI_Pakol_2_05",
			"CUP_H_TKI_Pakol_2_06",
			"CUP_H_TKI_SkullCap_01",
			"CUP_H_TKI_SkullCap_02",
			"CUP_H_TKI_SkullCap_03",
			"CUP_H_TKI_SkullCap_04",
			"CUP_H_TKI_SkullCap_05",
			"CUP_H_TKI_SkullCap_06",
			"CUP_H_NAPA_Fedora"
	
		};
	};

	class CivilianUniforms
	{
		name = "Uniforms";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] = 
		{
			//Uniforms
			"TRYK_HRP_UCP",
			"TRYK_HRP_USMC",
			"TRYK_HRP_khk",
			"TRYK_U_B_OD_OD_CombatUniform",
			"TRYK_U_B_OD_OD_R_CombatUniform",
			"TRYK_U_B_TANTAN_CombatUniform",
			"TRYK_U_B_TANTAN_R_CombatUniform",
			"TRYK_U_B_BLKBLK_CombatUniform",
			"TRYK_U_B_BLKBLK_R_CombatUniform",
			"TRYK_U_B_GRYOCP_CombatUniform",
			"TRYK_U_B_GRYOCP_R_CombatUniformTshirt",
			"TRYK_U_B_TANOCP_CombatUniform",
			"TRYK_U_B_TANOCP_R_CombatUniformTshirt",
			"TRYK_U_B_BLKOCP_CombatUniform",
			"TRYK_U_B_BLKOCP_R_CombatUniformTshirt",
			"TRYK_U_B_BLKTAN_CombatUniform",
			"TRYK_U_B_BLKTANR_CombatUniformTshirt",
			"TRYK_U_B_ODTAN_CombatUniform",
			"TRYK_U_B_ODTANR_CombatUniformTshirt",
			"TRYK_U_B_GRTAN_CombatUniform",
			"TRYK_U_B_GRTANR_CombatUniformTshirt",
			"TRYK_U_B_wood_CombatUniform",
			"TRYK_U_B_woodR_CombatUniformTshirt",
			"TRYK_U_B_wood3c_CombatUniform",
			"TRYK_U_B_wood3c_CombatUniformTshirt",
			"TRYK_U_B_MARPAT_WOOD_CombatUniform",
			"TRYK_U_B_MARPAT_WOOD_CombatUniformTshirt",
			"TRYK_U_B_WOOD_MARPAT_CombatUniform",
			"TRYK_U_B_WOOD_MARPAT_CombatUniformTshirt",
			"TRYK_U_B_woodtan_CombatUniform",
			"TRYK_U_B_woodtanR_CombatUniformTshirt",
			"TRYK_U_B_JSDF_CombatUniform",
			"TRYK_U_B_JSDF_CombatUniformTshirt",
			"TRYK_U_B_3CD_Delta_BDU",
			"TRYK_U_B_3CD_Delta_BDUTshirt",
			"TRYK_U_B_3CD_Ranger_BDU",
			"TRYK_U_B_3CD_Ranger_BDUTshirt",
			"TRYK_U_B_3CD_BLK_BDUTshirt",
			"TRYK_U_B_3CD_BLK_BDUTshirt2",
			"TRYK_U_B_ACU",
			"TRYK_U_B_ACUTshirt",
			"TRYK_U_B_MARPAT_Wood",
			"TRYK_U_B_MARPAT_Wood_Tshirt",
			"TRYK_U_B_MARPAT_Desert",
			"TRYK_U_B_MARPAT_Desert_Tshirt",
			"TRYK_U_B_MARPAT_Desert2",
			"TRYK_U_B_MARPAT_Desert2_Tshirt",
			"TRYK_U_B_3c",
			"TRYK_U_B_3cr",
			"TRYK_U_B_Sage_Tshirt",
			"TRYK_U_B_BLK3CD",
			"TRYK_U_B_BLK3CD_Tshirt",
			"TRYK_U_B_BLK",
			"TRYK_U_B_BLK_Tshirt",
			"TRYK_U_B_BLKTAN",
			"TRYK_U_B_BLKTAN_Tshirt",
			"TRYK_U_B_ODTAN",
			"TRYK_U_B_ODTAN_Tshirt",
			"TRYK_U_B_BLK_OD",
			"TRYK_U_B_BLK_OD_Tshirt",
			"TRYK_U_B_C01_Tsirt",
			"TRYK_U_B_C02_Tsirt",
			"TRYK_U_B_OD_BLK",
			"TRYK_U_B_OD_BLK_2",
			"TRYK_U_B_BLK_TAN_1",
			"TRYK_U_B_BLK_TAN_2",
			"TRYK_U_B_wh_tan_Rollup_CombatUniform",
			"TRYK_U_B_wh_OD_Rollup_CombatUniform",
			"TRYK_U_B_wh_blk_Rollup_CombatUniform",
			"TRYK_U_B_BLK_tan_Rollup_CombatUniform",
			"TRYK_U_B_BLK_OD_Rollup_CombatUniform",
			"TRYK_U_B_NATO_UCP_GRY_CombatUniform",
			"TRYK_U_B_NATO_UCP_GRY_R_CombatUniform",
			"TRYK_U_B_NATO_UCP_CombatUniform",
			"TRYK_U_B_NATO_UCP_R_CombatUniform",
			"TRYK_U_B_NATO_OCP_c_BLK_CombatUniform",
			"TRYK_U_B_NATO_OCP_BLK_c_R_CombatUniform",
			"TRYK_U_B_NATO_OCP_BLK_CombatUniform",
			"TRYK_U_B_NATO_OCP_BLK_R_CombatUniform",
			"TRYK_U_B_NATO_OCPD_CombatUniform",
			"TRYK_U_B_NATO_OCPD_R_CombatUniform",
			"TRYK_U_B_NATO_OCP_CombatUniform",
			"TRYK_U_B_NATO_OCP_R_CombatUniform",
			"TRYK_U_B_AOR1_Rollup_CombatUniform",
			"TRYK_U_B_AOR2_Rollup_CombatUniform",
			"TRYK_U_B_MTP_CombatUniform",
			"TRYK_U_B_MTP_R_CombatUniform",
			"TRYK_U_B_MTP_BLK_CombatUniform",
			"TRYK_U_B_MTP_BLK_R_CombatUniform",
			"TRYK_U_B_Woodland",
			"TRYK_U_B_Woodland_Tshirt",
			"TRYK_U_B_WDL_GRY_CombatUniform",
			"TRYK_U_B_WDL_GRY_R_CombatUniform",
			"TRYK_U_B_ARO1_GR_CombatUniform",
			"TRYK_U_B_ARO1_GR_R_CombatUniform",
			"TRYK_U_B_ARO1_GRY_CombatUniform",
			"TRYK_U_B_ARO1_GRY_R_CombatUniform",
			"TRYK_U_B_ARO1_CombatUniform",
			"TRYK_U_B_ARO1R_CombatUniform",
			"TRYK_U_B_ARO1_BLK_CombatUniform",
			"TRYK_U_B_ARO1_BLK_R_CombatUniform",
			"TRYK_U_B_ARO1_CBR_CombatUniform",
			"TRYK_U_B_ARO1_CBR_R_CombatUniform",
			"TRYK_U_B_ARO2_CombatUniform",
			"TRYK_U_B_ARO2R_CombatUniform",
			"TRYK_U_B_AOR2_BLK_CombatUniform",
			"TRYK_U_B_AOR2_BLK_R_CombatUniform",
			"TRYK_U_B_AOR2_OD_CombatUniform",
			"TRYK_U_B_AOR2_OD_R_CombatUniform",
			"TRYK_U_B_AOR2_GRY_CombatUniform",
			"TRYK_U_B_AOR2_GRY_R_CombatUniform",
			"TRYK_U_B_Snow_CombatUniform",
			"TRYK_U_B_Snowt",
			"TRYK_U_B_Denim_T_WH",
			"TRYK_U_B_Denim_T_BK",
			"TRYK_U_B_BLK_T_WH",
			"TRYK_U_B_BLK_T_BK",
			"TRYK_U_B_RED_T_BR",
			"TRYK_U_B_Denim_T_BG_WH",
			"TRYK_U_B_Denim_T_BG_BK",
			"TRYK_U_B_BLK_T_BG_WH",
			"TRYK_U_B_BLK_T_BG_BK",
			"TRYK_U_B_RED_T_BG_BR",
			"TRYK_U_B_fleece",
			"TRYK_U_B_fleece_UCP",
			"TRYK_U_B_UCP_PCUs",
			"TRYK_U_B_GRY_PCUs",
			"TRYK_U_B_Wood_PCUs",
			"TRYK_U_B_PCUs",
			"TRYK_U_B_UCP_PCUs_R",
			"TRYK_U_B_GRY_PCUs_R",
			"TRYK_U_B_Wood_PCUs_R",
			"TRYK_U_B_PCUs_R",
			"TRYK_U_B_PCUGs",
			"TRYK_U_B_PCUODs",
			"TRYK_U_B_PCUGs_gry",
			"TRYK_U_B_PCUGs_BLK",
			"TRYK_U_B_PCUGs_OD",
			"TRYK_U_B_PCUGs_gry_R",
			"TRYK_U_B_PCUGs_BLK_R",
			"TRYK_U_B_PCUGs_OD_R",
			"TRYK_U_Bts_GRYGRY_PCUs",
			"TRYK_U_Bts_UCP_PCUs",
			"TRYK_U_Bts_Wood_PCUs",
			"TRYK_U_Bts_PCUs",
			"TRYK_U_pad_j",
			"TRYK_U_pad_j_blk",
			"TRYK_U_pad_hood_Cl",
			"TRYK_U_pad_hood_Cl_blk",
			"TRYK_U_pad_hood_tan",
			"TRYK_U_pad_hood_Blk",
			"TRYK_U_pad_hood_CSATBlk",
			"TRYK_U_pad_hood_Blod",
			"TRYK_U_pad_hood_odBK",
			"TRYK_U_pad_hood_BKT2",
			"TRYK_hoodie_Blk",
			"TRYK_hoodie_FR",
			"TRYK_hoodie_Wood",
			"TRYK_hoodie_3c",
			"TRYK_T_camo_tan",
			"TRYK_T_camo_3c",
			"TRYK_T_camo_Wood",
			"TRYK_T_camo_wood_marpat",
			"TRYK_T_camo_Desert_marpat",
			"TRYK_T_camo_3c_BG",
			"TRYK_T_camo_Wood_BG",
			"TRYK_T_camo_wood_marpat_BG",
			"TRYK_T_camo_desert_marpat_BG",
			"TRYK_T_PAD",
			"TRYK_T_OD_PAD",
			"TRYK_T_TAN_PAD",
			"TRYK_T_BLK_PAD",
			"TRYK_T_T2_PAD",
			"TRYK_T_CSAT_PAD",
			"TRYK_U_nohoodPcu_gry",
			"TRYK_U_hood_nc",
			"TRYK_U_hood_mc",
			"TRYK_U_denim_hood_blk",
			"TRYK_U_denim_hood_mc",
			"TRYK_U_denim_hood_3c",
			"TRYK_U_denim_hood_nc",
			"TRYK_U_denim_jersey_blu",
			"TRYK_U_denim_jersey_blk",
			"TRYK_shirts_PAD",
			"TRYK_shirts_OD_PAD",
			"TRYK_shirts_TAN_PAD",
			"TRYK_shirts_BLK_PAD",
			"TRYK_shirts_PAD_BK",
			"TRYK_shirts_OD_PAD_BK",
			"TRYK_shirts_TAN_PAD_BK",
			"TRYK_shirts_BLK_PAD_BK",
			"TRYK_shirts_PAD_BLW",
			"TRYK_shirts_OD_PAD_BLW",
			"TRYK_shirts_TAN_PAD_BLW",
			"TRYK_shirts_BLK_PAD_BLW",
			"TRYK_shirts_PAD_YEL",
			"TRYK_shirts_OD_PAD_YEL",
			"TRYK_shirts_TAN_PAD_YEL",
			"TRYK_shirts_BLK_PAD_YEL",
			"TRYK_shirts_PAD_RED2",
			"TRYK_shirts_OD_PAD_RED2",
			"TRYK_shirts_TAN_PAD_RED2",
			"TRYK_shirts_BLK_PAD_RED2",
			"TRYK_shirts_PAD_BLU3",
			"TRYK_shirts_OD_PAD_BLU3",
			"TRYK_shirts_TAN_PAD_BLU3",
			"TRYK_shirts_BLK_PAD_BLU3",
			"TRYK_shirts_DENIM_R",
			"TRYK_shirts_DENIM_BL",
			"TRYK_shirts_DENIM_BK",
			"TRYK_shirts_DENIM_WH",
			"TRYK_shirts_DENIM_BWH",
			"TRYK_shirts_DENIM_RED2",
			"TRYK_shirts_DENIM_WHB",
			"TRYK_shirts_DENIM_ylb",
			"TRYK_shirts_DENIM_od",
			"TRYK_shirts_DENIM_R_Sleeve",
			"TRYK_shirts_DENIM_BL_Sleeve",
			"TRYK_shirts_DENIM_BK_Sleeve",
			"TRYK_shirts_DENIM_WH_Sleeve",
			"TRYK_shirts_DENIM_BWH_Sleeve",
			"TRYK_shirts_DENIM_RED2_Sleeve",
			"TRYK_shirts_DENIM_WHB_Sleeve",
			"TRYK_shirts_DENIM_ylb_Sleeve",
			"TRYK_shirts_DENIM_od_Sleeve",
			"TRYK_shirts_PAD_BL",
			"TRYK_shirts_OD_PAD_BL",
			"TRYK_shirts_TAN_PAD_BL",
			"TRYK_shirts_BLK_PAD_BL",
			"TRYK_U_taki_wh",
			"TRYK_U_taki_COY",
			"TRYK_U_taki_BL",
			"TRYK_U_taki_BLK",
			"TRYK_U_Bts_PCUGs",
			"TRYK_U_Bts_PCUODs",
			"TRYK_U_taki_G_WH",
			"TRYK_U_taki_G_COY",
			"TRYK_U_taki_G_BL",
			"TRYK_U_taki_G_BLK",
			"TRYK_U_B_PCUHs",
			"TRYK_U_B_PCUGHs",
			"TRYK_U_B_PCUODHs",
			"TRYK_B_USMC_R",
			"TRYK_B_USMC_R_ROLL",
			"TRYK_ZARATAKI",
			"TRYK_ZARATAKI2",
			"TRYK_ZARATAKI3",
			"TRYK_B_TRYK_UCP_T",
			"TRYK_B_TRYK_3C_T",
			"TRYK_B_TRYK_MTP_T",
			"TRYK_B_TRYK_OCP_T",
			"TRYK_B_TRYK_OCP_D_T",
			"TRYK_DMARPAT_T",
			"TRYK_C_AOR2_T",
			"TRYK_U_B_Sage_T",
			"TRYK_U_B_Wood_T",
			"TRYK_U_B_BLTAN_T",
			"TRYK_U_B_BLOD_T",
			"TRYK_OVERALL_flesh",
			"TRYK_OVERALL_nok_flesh",
			"TRYK_OVERALL_SAGE_BLKboots",
			"TRYK_OVERALL_SAGE_BLKboots_nk_blk",
			"TRYK_OVERALL_SAGE_BLKboots_nk",
			"TRYK_OVERALL_SAGE_BLKboots_nk_blk2",
			"TRYK_OVERALL_SAGE",
			"TRYK_SUITS_BLK_F",
			"TRYK_SUITS_BR_F",
			"TRYK_U_B_PCUHsW",
			"TRYK_U_B_PCUHsW2",
			"TRYK_U_B_PCUHsW3",
			"TRYK_U_B_PCUHsW3nh",
			"TRYK_U_B_PCUHsW4",
			"TRYK_U_B_PCUHsW5",
			"TRYK_U_B_PCUHsW6",
			"rhssaf_uniform_m10_digital",
			"rhssaf_uniform_m10_digital_summer",
			"rhssaf_uniform_m10_digital_desert",
			"rhssaf_uniform_m10_digital_tan_boots",
			"rhssaf_uniform_m93_oakleaf",
			"rhssaf_uniform_m93_oakleaf_summer",
			"CUP_O_TKI_Khet_Partug_01",
			"CUP_O_TKI_Khet_Partug_02",
			"CUP_O_TKI_Khet_Partug_03",
			"CUP_O_TKI_Khet_Partug_04",
			"CUP_O_TKI_Khet_Partug_05",
			"CUP_O_TKI_Khet_Partug_06",
			"CUP_O_TKI_Khet_Partug_07",
			"CUP_O_TKI_Khet_Partug_08",
			"CUP_O_TKI_Khet_Jeans_01",
			"CUP_O_TKI_Khet_Jeans_02",
			"CUP_O_TKI_Khet_Jeans_03",
			"CUP_O_TKI_Khet_Jeans_04",
			"CUP_U_C_Citizen_01",
			"CUP_U_C_Citizen_02",
			"CUP_U_C_Citizen_03",
			"CUP_U_C_Citizen_04",
			"CUP_U_C_Worker_01",
			"CUP_U_C_Worker_02",
			"CUP_U_C_Worker_03",
			"CUP_U_C_Worker_04",
			"CUP_U_C_Profiteer_01",
			"CUP_U_C_Profiteer_02",
			"CUP_U_C_Profiteer_03",
			"CUP_U_C_Profiteer_04",
			"CUP_U_C_Woodlander_01",
			"CUP_U_C_Woodlander_02",
			"CUP_U_C_Woodlander_03",
			"CUP_U_C_Woodlander_04",
			"CUP_U_C_Villager_01",
			"CUP_U_C_Villager_02",
			"CUP_U_C_Villager_03",
			"CUP_U_C_Villager_04",
			"CUP_U_I_RACS_Desert_1",
			"CUP_U_I_RACS_Desert_2",
			"CUP_U_I_RACS_Urban_1",
			"CUP_U_I_RACS_Urban_2",
			"CUP_U_O_SLA_Officer",
			"CUP_U_O_SLA_Officer_Suit",
			"CUP_U_O_SLA_MixedCamo",
			"CUP_U_O_SLA_Green",
			"CUP_U_O_SLA_Urban",
			"CUP_U_O_SLA_Desert"

		};
	};

	class CivilianVests
	{
		name = "Vests";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] = 
		{
			//Vests
			"TRYK_Hrp_vest_ucp",
			"TRYK_Hrp_vest_od",
			//"TRYK_V_PlateCarrier_JSDF",// Missing icon
			"TRYK_V_ArmorVest_AOR1",
			"TRYK_V_ArmorVest_AOR2",
			"TRYK_V_ArmorVest_coyo",
			"TRYK_V_ArmorVest_Brown",
			"TRYK_V_ArmorVest_CBR",
			"TRYK_V_ArmorVest_khk",
			"TRYK_V_ArmorVest_rgr",
			"TRYK_V_ArmorVest_green",
			"TRYK_V_ArmorVest_tan",
			"TRYK_V_ArmorVest_Delta",
			"TRYK_V_ArmorVest_Ranger",
			"TRYK_V_ArmorVest_AOR1_2",
			"TRYK_V_ArmorVest_AOR2_2",
			"TRYK_V_ArmorVest_coyo2",
			"TRYK_V_ArmorVest_Brown2",
			"TRYK_V_ArmorVest_cbr2",
			"TRYK_V_ArmorVest_khk2",
			"TRYK_V_ArmorVest_rgr2",
			"TRYK_V_ArmorVest_green2",
			"TRYK_V_ArmorVest_tan2",
			"TRYK_V_ArmorVest_Delta2",
			"TRYK_V_ArmorVest_Ranger2",
			"TRYK_V_PlateCarrier_blk",
			"TRYK_V_PlateCarrier_oli",
			"TRYK_V_PlateCarrier_coyo",
			"TRYK_V_PlateCarrier_wood",
			"TRYK_V_PlateCarrier_ACU",
			"TRYK_V_TacVest_coyo",
			"TRYK_V_harnes_blk_L",
			"TRYK_V_harnes_od_L",
			"TRYK_V_harnes_TAN_L",
			"TRYK_V_PlateCarrier_blk_L",
			"TRYK_V_PlateCarrier_wood_L",
			"TRYK_V_PlateCarrier_ACU_L",
			"TRYK_V_PlateCarrier_coyo_L",
			"TRYK_V_ChestRig_L",
			"TRYK_V_ChestRig",
			//"TRYK_V_Bulletproof",// Has no capacity
			//"TRYK_V_Bulletproof_BLK",// Has no capacity
			//"TRYK_V_Bulletproof_BL",// Has no capacity
			"TRYK_V_IOTV_BLK",
			"TRYK_V_tacv1M_BK",
			"TRYK_V_tacv1MLC_BK",
			"TRYK_V_tacv1",
			"TRYK_V_tacv1_CY",
			"TRYK_V_tacv1_BK",
			"TRYK_V_tacv1_P_BK",
			"TRYK_V_tacv1_SHERIFF_BK",
			"TRYK_V_tacv1_FBI_BK",
			"TRYK_V_tacv1LP_BK",
			"TRYK_V_tacv1LSRF_BK",
			"TRYK_V_tacv1LC_BK",
			"TRYK_V_tacv1LC_CY",
			"TRYK_V_tacv1LC_OD",
			"TRYK_V_tacv1LC_FBI_BK",
			"TRYK_V_tacv1LC_SRF_BK",
			"TRYK_V_tacv1LC_SRF_OD",
			"TRYK_V_tacv1LC_P_BK",
			"TRYK_V_PlateCarrier_POLICE",
			"TRYK_V_ArmorVest_HRT_B",
			"TRYK_V_ArmorVest_HRT_OD",
			"TRYK_V_ArmorVest_HRT2_B",
			"TRYK_V_ArmorVest_HRT2_OD",
			"TRYK_V_ArmorVest_Winter",
			"TRYK_V_Sheriff_BA_OD",
			"TRYK_V_tacv10_BK",
			"TRYK_V_tacv10_OD",
			"TRYK_V_tacv10_TN",
			"TRYK_V_tacv10LC_BK",
			"TRYK_V_tacv10LC_OD",
			"TRYK_V_tacv10LC_TN",
			"TRYK_V_tacv1L_BK",
			"TRYK_V_tacv1L_OD",
			"TRYK_V_tacv1L_CY",
			"TRYK_V_tacv1LC_FBI2_BK",
			"TRYK_V_tacv1LC_SRF2_BK",
			"TRYK_V_tacv1LC_SRF2_OD",
			"TRYK_V_tacv1LC_P2_BK",
			"TRYK_V_tacv1_MSL_BK",
			"TRYK_V_tacv1_MSL_NV",
			"TRYK_V_tacv1LMSL_BK",
			"TRYK_V_tacv1LMSL_NV",
			"TRYK_V_tacv1LC_MSL_BK",
			"TRYK_V_tacv1LC_MSL_NV",
			"TRYK_V_tacSVD_BK",
			"TRYK_V_tacSVD_OD",
			"TRYK_V_Sheriff_BA_TL",
			"TRYK_V_Sheriff_BA_TBL",
			"TRYK_V_Sheriff_BA_TCL",
			"TRYK_V_Sheriff_BA_TL2",
			"TRYK_V_Sheriff_BA_TBL2",
			"TRYK_V_Sheriff_BA_TCL2",
			"TRYK_V_Sheriff_BA_T",
			"TRYK_V_Sheriff_BA_TB",
			"TRYK_V_Sheriff_BA_T2",
			"TRYK_V_Sheriff_BA_TB2",
			"TRYK_V_Sheriff_BA_T3",
			"TRYK_V_Sheriff_BA_TB3",
			"TRYK_V_Sheriff_BA_T4",
			"TRYK_V_Sheriff_BA_TB4",
			"TRYK_V_Sheriff_BA_T5",
			"TRYK_V_Sheriff_BA_TB5",
			"TRYK_V_Sheriff_BA_TBL3_BK",
			"TRYK_V_Sheriff_BA_TBL3_OD",
			"TRYK_V_Sheriff_BA_TBL3_TN",
			"TRYK_LOC_AK_chestrig_OD",
			"TRYK_LOC_AK_chestrig_TAN",
			"rhssaf_vest_md98_woodland",
			"rhssaf_vest_md98_md2camo",
			"rhssaf_vest_md98_digital",
			"rhssaf_vest_md98_officer",
			"rhssaf_vest_md98_rifleman",
			"rhssaf_vest_otv_md2camo",
			"rhssaf_vest_md99_md2camo_rifleman",
			"rhssaf_vest_md99_digital_rifleman",
			"rhssaf_vest_md99_woodland_rifleman",
			"rhssaf_vest_md99_md2camo",
			"rhssaf_vest_md99_digital",
			"rhssaf_vest_md99_woodland",
			"CUP_V_OI_TKI_Jacket1_01",
			"CUP_V_OI_TKI_Jacket1_02",
			"CUP_V_OI_TKI_Jacket1_03",
			"CUP_V_OI_TKI_Jacket1_04",
			"CUP_V_OI_TKI_Jacket1_05",
			"CUP_V_OI_TKI_Jacket1_06",
			"CUP_V_OI_TKI_Jacket2_01",
			"CUP_V_OI_TKI_Jacket2_02",
			"CUP_V_OI_TKI_Jacket2_03",
			"CUP_V_OI_TKI_Jacket2_04",
			"CUP_V_OI_TKI_Jacket2_05",
			"CUP_V_OI_TKI_Jacket2_06",
			"CUP_V_OI_TKI_Jacket3_01",
			"CUP_V_OI_TKI_Jacket3_02",
			"CUP_V_OI_TKI_Jacket3_03",
			"CUP_V_OI_TKI_Jacket3_04",
			"CUP_V_OI_TKI_Jacket3_05",
			"CUP_V_OI_TKI_Jacket3_06",
			"CUP_V_OI_TKI_Jacket4_01",
			"CUP_V_OI_TKI_Jacket4_02",
			"CUP_V_OI_TKI_Jacket4_03",
			"CUP_V_OI_TKI_Jacket4_04",
			"CUP_V_OI_TKI_Jacket4_05",
			"CUP_V_OI_TKI_Jacket4_06",
			"CUP_V_O_SLA_Carrier_Belt",
			"CUP_V_O_SLA_Carrier_Belt02",
			"CUP_V_O_SLA_Carrier_Belt03",
			"CUP_V_O_SLA_Flak_Vest01",
			"CUP_V_O_SLA_Flak_Vest02",
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_V_O_TK_CrewBelt",
			"CUP_V_O_TK_OfficerBelt",
			"CUP_V_O_TK_OfficerBelt2",
			"CUP_V_O_TK_Vest_1",
			"CUP_V_O_TK_Vest_2"
		};
	};

	class CivilianBackpacks
	{
		name = "Backpacks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] = 
		{
			//BackPacks
			"TRYK_B_AssaultPack_UCP",
			"TRYK_B_AssaultPack_Type2camo",
			"TRYK_B_AssaultPack_MARPAT_Desert",
			"TRYK_B_AssaultPack_MARPAT_Wood",
			"TRYK_B_Kitbag_Base",
			"TRYK_B_Kitbag_blk",
			"TRYK_B_Kitbag_aaf",
			"TRYK_B_Carryall_blk",
			"TRYK_B_Carryall_wh",
			"TRYK_B_Carryall_wood",
			"TRYK_B_Carryall_JSDF",
			"TRYK_B_Kitbag_Base_JSDF",
			"TRYK_B_Coyotebackpack",
			"TRYK_B_Coyotebackpack_OD",
			"TRYK_B_Coyotebackpack_BLK",
			"TRYK_B_Coyotebackpack_WH",
			"TRYK_B_Alicepack",
			"TRYK_B_Medbag",
			"TRYK_B_Medbag_OD",
			"TRYK_B_Medbag_BK",
			"TRYK_B_Medbag_ucp",
			"TRYK_B_Belt",
			"TRYK_B_Belt_BLK",
			"TRYK_B_Belt_CYT",
			"TRYK_B_Belt_tan",
			"TRYK_B_Belt_br",
			"TRYK_B_Belt_GR",
			"TRYK_B_Belt_AOR1",
			"TRYK_B_Belt_AOR2",
			"TRYK_B_BAF_BAG_BLK",
			"TRYK_B_BAF_BAG_CYT",
			"TRYK_B_BAF_BAG_OD",
			"TRYK_B_BAF_BAG_rgr",
			"TRYK_B_BAF_BAG_mcamo",
			"TRYK_B_tube_cyt",
			"TRYK_B_tube_od",
			"TRYK_B_tube_blk",
			"TRYK_B_FieldPack_Wood",
			"TRYK_Winter_pack",
			"rhssaf_Kitbag_base",
			"rhssaf_kitbag_md2camo",
			"rhssaf_kitbag_digital",
			"rhssaf_kitbag_smb",
			"CUP_B_ACRPara_m95",
			"CUP_B_AssaultPack_ACU",
			"CUP_B_AssaultPack_Black",
			"CUP_B_AssaultPack_Coyote",
			"CUP_B_Bergen_BAF",
			"CUP_B_CivPack_WDL",
			"CUP_B_GER_Pack_Flecktarn",
			"CUP_B_GER_Pack_Tropentarn",
			"CUP_B_HikingPack_Civ",
			"CUP_B_MOLLE_WDL"
		};
	};
	

	// Military
	
	
	class MilitaryUniforms
	{
		name = "Military Uniforms";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\uniform_ca.paa";
		items[] =
		{
			"rhs_uniform_FROG01_m81",
			"rhs_uniform_FROG01_d",
			"rhs_uniform_FROG01_wd",
			"rhs_uniform_cu_ocp",
			"rhs_uniform_cu_ucp",
			"rhs_uniform_cu_ocp_101st",
			"rhs_uniform_cu_ocp_10th",
			"rhs_uniform_cu_ocp_1stcav",
			"rhs_uniform_cu_ocp_82nd",
			"rhs_uniform_cu_ucp_101st",
			"rhs_uniform_cu_ucp_10th",
			"rhs_uniform_cu_ucp_1stcav",
			"rhs_uniform_cu_ucp_82nd",
			"rhs_uniform_cu_ocp_patchless",
	        "rhs_uniform_cu_ucp_patchless",
			// Added by ElShotte - 5 Items
			"rhs_uniform_g3_m81",
			"rhs_uniform_g3_blk",
			"rhs_uniform_g3_mc",
			"rhs_uniform_g3_rgr",
			"rhs_uniform_g3_tan",
			"rhsgref_uniform_alpenflage",
			"rhsgref_uniform_flecktarn",
			"rhsgref_uniform_para_ttsko_mountain",
			"rhsgref_uniform_para_ttsko_oxblood",
			"rhsgref_uniform_para_ttsko_urban",
			"rhsgref_uniform_reed",
			"rhsgref_uniform_specter",
			"rhsgref_uniform_tigerstripe",
			"rhsgref_uniform_ttsko_forest",
			"rhsgref_uniform_ttsko_mountain",
			"rhsgref_uniform_ttsko_urban",
			"rhsgref_uniform_vsr",
			"rhsgref_uniform_woodland",
			"rhsgref_uniform_woodland_olive"
		};
	};

	class MilitaryVests
	{
		name = "Military Vests";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\vest_ca.paa";
		items[] =
		{

			"rhsusf_iotv_ucp",
			"rhsusf_iotv_ucp_grenadier",
			"rhsusf_iotv_ucp_medic",
			"rhsusf_iotv_ucp_repair",
			"rhsusf_iotv_ucp_rifleman",
			"rhsusf_iotv_ucp_SAW",
			"rhsusf_iotv_ucp_squadleader",
			"rhsusf_iotv_ucp_teamleader",
			"rhsusf_iotv_ocp",
			"rhsusf_iotv_ocp_grenadier",
			"rhsusf_iotv_ocp_medic",
			"rhsusf_iotv_ocp_repair",
			"rhsusf_iotv_ocp_rifleman",
			"rhsusf_iotv_ocp_SAW",
			"rhsusf_iotv_ocp_squadleader",
			"rhsusf_iotv_ocp_teamleader",
			//added by chainsaw - 2
			"rhsusf_spc",
			"rhsusf_spc_mg",
			// Added by ElShotte - 12 Items
			"rhsusf_spc_marksman",
			"rhsusf_spc_corpsman",
			"rhsusf_spc_patchless",
			"rhsusf_spc_squadleader",
			"rhsusf_spc_teamleader",
			"rhsusf_spc_light",
			"rhsusf_spc_rifleman",
			"rhsusf_spc_iar",
			"rhsusf_spcs_ocp_rifleman",
			"rhsusf_spcs_ocp",
			"rhsusf_spcs_ucp_rifleman",
			"rhsusf_spcs_ucp",
			"rhsgref_6b23",
			"rhsgref_6b23_khaki",
			"rhsgref_6b23_khaki_medic",
			"rhsgref_6b23_khaki_nco",
			"rhsgref_6b23_khaki_officer",
			"rhsgref_6b23_khaki_rifleman",
			"rhsgref_6b23_khaki_sniper",
			"rhsgref_6b23_ttsko_digi",
			"rhsgref_6b23_ttsko_digi_medic",
			"rhsgref_6b23_ttsko_digi_nco",
			"rhsgref_6b23_ttsko_digi_officer",
			"rhsgref_6b23_ttsko_digi_rifleman",
			"rhsgref_6b23_ttsko_digi_sniper",
			"rhsgref_6b23_ttsko_forest",
			"rhsgref_6b23_ttsko_forest_rifleman",
			"rhsgref_6b23_ttsko_mountain",
			"rhsgref_6b23_ttsko_mountain_medic",
			"rhsgref_6b23_ttsko_mountain_nco",
			"rhsgref_6b23_ttsko_mountain_officer",
			"rhsgref_6b23_ttsko_mountain_rifleman",
			"rhsgref_6b23_ttsko_mountain_sniper",
			"rhsgref_otv_digi",
			"rhsgref_otv_khaki"

		};
	};

	class MilitaryHeadgear
	{
		name = "Military Headgear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\headgear_ca.paa";
		items[] =
		{

			"rhs_Booniehat_m81",
			"rhs_Booniehat_marpatd",
			"rhs_Booniehat_marpatwd",
			"rhs_Booniehat_ocp",
			"rhs_Booniehat_ucp",
			"rhsusf_Bowman",
			"rhsusf_ach_bare",
			"rhsusf_ach_bare_des",
			"rhsusf_ach_bare_des_ess",
			"rhsusf_ach_bare_des_headset",
			"rhsusf_ach_bare_des_headset_ess",
			"rhsusf_ach_bare_ess",
			"rhsusf_ach_bare_headset",
			"rhsusf_ach_bare_headset_ess",
			"rhsusf_ach_bare_semi",
			"rhsusf_ach_bare_semi_ess",
			"rhsusf_ach_bare_semi_headset",
			"rhsusf_ach_bare_semi_headset_ess",
			"rhsusf_ach_bare_tan",
			"rhsusf_ach_bare_tan_ess",
			"rhsusf_ach_bare_tan_headset",
			"rhsusf_ach_bare_tan_headset_ess",
			"rhsusf_ach_bare_wood",
			"rhsusf_ach_bare_wood_ess",
			"rhsusf_ach_bare_wood_headset",
			"rhsusf_ach_bare_wood_headset_ess",
			"rhsusf_ach_helmet_ESS_ocp",
			"rhsusf_ach_helmet_ESS_ucp",
			"rhsusf_ach_helmet_M81",
			"rhsusf_ach_helmet_camo_ocp",
			"rhsusf_ach_helmet_headset_ess_ocp",
			"rhsusf_ach_helmet_headset_ess_ucp",
			"rhsusf_ach_helmet_headset_ocp",
			"rhsusf_ach_helmet_headset_ucp",
			"rhsusf_ach_helmet_ocp",
			"rhsusf_ach_helmet_ocp_norotos",
			"rhsusf_ach_helmet_ucp",
			"rhsusf_ach_helmet_ucp_norotos",
			"rhsusf_bowman_cap",
			"rhsusf_lwh_helmet_M1942",
			"rhsusf_lwh_helmet_marpatd",
			"rhsusf_lwh_helmet_marpatd_ess",
			"rhsusf_lwh_helmet_marpatd_headset",
			"rhsusf_lwh_helmet_marpatwd",
			"rhsusf_lwh_helmet_marpatwd_ess",
			"rhsusf_lwh_helmet_marpatwd_headset",
			"rhsusf_mich_bare",
			"rhsusf_mich_bare_alt",
			"rhsusf_mich_bare_alt_semi",
			"rhsusf_mich_bare_alt_tan",
			"rhsusf_mich_bare_headset",
			"rhsusf_mich_bare_norotos",
			"rhsusf_mich_bare_norotos_alt",
			"rhsusf_mich_bare_norotos_alt_headset",
			"rhsusf_mich_bare_norotos_alt_semi",
			"rhsusf_mich_bare_norotos_alt_semi_headset",
			"rhsusf_mich_bare_norotos_alt_tan",
			"rhsusf_mich_bare_norotos_alt_tan_headset",
			"rhsusf_mich_bare_norotos_arc",
			"rhsusf_mich_bare_norotos_arc_alt",
			"rhsusf_mich_bare_norotos_arc_alt_headset",
			"rhsusf_mich_bare_norotos_arc_alt_semi",
			"rhsusf_mich_bare_norotos_arc_alt_semi_headset",
			"rhsusf_mich_bare_norotos_arc_alt_tan",
			"rhsusf_mich_bare_norotos_arc_alt_tan_headset",
			"rhsusf_mich_bare_norotos_arc_headset",
			"rhsusf_mich_bare_norotos_arc_semi",
			"rhsusf_mich_bare_norotos_arc_semi_headset",
			"rhsusf_mich_bare_norotos_arc_tan",
			"rhsusf_mich_bare_norotos_headset",
			"rhsusf_mich_bare_norotos_semi",
			"rhsusf_mich_bare_norotos_semi_headset",
			"rhsusf_mich_bare_norotos_tan",
			"rhsusf_mich_bare_norotos_tan_headset",
			"rhsusf_mich_bare_semi",
			"rhsusf_mich_bare_semi_headset",
			"rhsusf_mich_bare_tan",
			"rhsusf_mich_bare_tan_headset",
			"rhsusf_mich_helmet_marpatd_alt_headset",
			"rhsusf_mich_helmet_marpatd_headset",
			"rhsusf_mich_helmet_marpatd_norotos",
			"rhsusf_mich_helmet_marpatd_norotos_arc",
			"rhsusf_mich_helmet_marpatd_norotos_arc_headset",
			"rhsusf_mich_helmet_marpatd_norotos_headset",
			"rhsusf_mich_helmet_marpatwd",
			"rhsusf_mich_helmet_marpatwd_alt",
			"rhsusf_mich_helmet_marpatwd_alt_headset",
			"rhsusf_mich_helmet_marpatwd_headset",
			"rhsusf_mich_helmet_marpatwd_norotos",
			"rhsusf_mich_helmet_marpatwd_norotos_arc",
			"rhsusf_mich_helmet_marpatwd_norotos_arc_headset",
			"rhsusf_mich_helmet_marpatwd_norotos_headset",
			// added by chainsaw - 13
			"rhsusf_patrolcap_ocp",
			"rhsusf_patrolcap_ucp",
			"rhsusf_opscore_01",
			"rhsusf_opscore_01_tan",
			"rhsusf_opscore_02_tan",
			"rhsusf_opscore_03_ocp",
			"rhsusf_opscore_04_ocp",
			"rhsusf_cvc_helmet",
			"rhsusf_cvc_ess",
			"rhsusf_hgu56p",
			"rhsusf_hgu56p_mask",
			"rhsusf_cvc_green_helmet",
			"rhsusf_cvc_green_ess",
			// Added by ElShotte - 41 Items
			"rhsusf_opscore_bk_pelt",
			"rhsusf_opscore_bk",
			"rhsusf_opscore_coy_cover",
			"rhsusf_opscore_coy_cover_pelt",
			"rhsusf_opscore_fg",
			"rhsusf_opscore_fg_pelt",
			"rhsusf_opscore_fg_pelt_cam",
			"rhsusf_opscore_fg_pelt_nsw",
			"rhsusf_opscore_mc",
			"rhsusf_opscore_mc_pelt",
			"rhsusf_opscore_mc_pelt_nsw",
			"rhsusf_opscore_mc_cover",
			"rhsusf_opscore_mc_cover_pelt",
			"rhsusf_opscore_mc_cover_pelt_nsw",
			"rhsusf_opscore_mc_cover_pelt_cam",
			"rhsusf_opscore_paint",
			"rhsusf_opscore_paint_pelt",
			"rhsusf_opscore_paint_pelt_nsw",
			"rhsusf_opscore_paint_pelt_nsw_cam",
			"rhsusf_opscore_rg_cover",
			"rhsusf_opscore_rg_cover_pelt",
			"rhsusf_opscore_ut",
			"rhsusf_opscore_ut_pelt",
			"rhsusf_opscore_ut_pelt_cam",
			"rhsusf_opscore_ut_pelt_nsw",
			"rhsusf_opscore_ut_pelt_nsw_cam",
			"rhsusf_opscore_mar_ut_pelt",
			"rhsusf_opscore_mar_ut",
			"rhsusf_opscore_mar_fg_pelt",
			"rhsusf_opscore_mar_fg",
			"rhsusf_protech_helmet",
			"rhsusf_protech_helmet_ess",
			"rhsusf_protech_helmet_rhino",
			"rhsusf_protech_helmet_rhino_ess",
			"rhsgref_6b27m",
			"rhsgref_6b27m_ttsko_digi",
			"rhsgref_6b27m_ttsko_forest",
			"rhsgref_6b27m_ttsko_mountain",
			"rhsgref_6b27m_ttsko_urban",
			"rhsgref_Booniehat_alpen",
			"rhsgref_fieldcap",
			"rhsgref_fieldcap_ttsko_digi",
			"rhsgref_fieldcap_ttsko_forest",
			"rhsgref_fieldcap_ttsko_mountain",
			"rhsgref_fieldcap_ttsko_urban",
			"rhsgref_patrolcap_specter",
			"rhsgref_ssh68",
			"rhsgref_ssh68_emr",
			"rhsgref_ssh68_ttsko_digi",
			"rhsgref_ssh68_ttsko_forest",
			"rhsgref_ssh68_ttsko_mountain",
			"rhsgref_ssh68_un"
		};
	};

	class MilitaryBackpacks
	{
		name = "Military Backpacks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
		items[] =
		{
			"rhsusf_assault_eagleaiii_coy",
			"rhsusf_assault_eagleaiii_ocp",
			"rhsusf_assault_eagleaiii_ucp",
			"rhsusf_falconii_coy",
			"rhsusf_falconii_mc",
			"rhsusf_falconii",
			"CUP_B_RUS_Backpack",
			"CUP_B_USMC_AssaultPack",
			"CUP_B_USMC_MOLLE",
			"CUP_B_USPack_Black",
			"CUP_B_USPack_Coyote"

		};
	};

	class MilitaryMedical
	{
		name = "Hospital";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			// "ACE_personalAidKit",
			"ACE_morphine",
			"ACE_epinephrine",
			"ACE_fieldDressing",
			"ACE_bloodIV_250",
			"ACE_bloodIV_500",
			"ACE_bloodIV",
			"ACE_bodyBag",
			"ACE_tourniquet",
			"Exile_Item_Defibrillator"
		};
	};

	class MilitaryEquipment
	{
		name = "Military Equipment";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"B_Parachute",
			"ACE_NonSteerableParachute",
			"ACE_DAGR",
			"ACE_Kestrel4500",
			"ACE_ATragMX",
			"ACE_HuntIR_monitor",
			"ACE_HuntIR_M203",
			"ACE_IR_Strobe_Item",
			"ACE_DefusalKit",
			"ACE_Cellphone",
			"ACE_Clacker",
			"ACE_CableTie",
			"ACE_MapTools",
			"ACE_Flashlight_MX991",
			"ACE_RangeCard",
			"ACE_Flashlight_XL50",
			"ACE_VectorDay",
			"ACE_SpottingScope",
			"ACE_Tripod",
			"ACE_NVG_Gen1",
			"ACE_NVG_Gen2",
			"lerca_1200_black",
			"ACE_Vector",
			"ACE_Altimeter",
			"RHS_pdu4",
			"ACE_microDAGR",
			"ACE_M26_Clacker",
			"ACE_NVG_Gen4",
			"ACE_NVG_Wide"		
		};
	};
	
	class AssaultRifles
	{
		name = "Assault Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"arifle_Katiba_C_F",
			"arifle_Katiba_F",
			"arifle_Katiba_GL_F",
			"arifle_Mk20_F",
			"arifle_Mk20_GL_F",
			"arifle_Mk20_GL_plain_F",
			"arifle_Mk20_plain_F",
			"arifle_Mk20C_F",
			"arifle_Mk20C_plain_F",
			"arifle_MX_Black_F",
			"arifle_MX_F",
			"arifle_MX_GL_Black_F",
			"arifle_MX_GL_F",
			"arifle_MXC_Black_F",
			"arifle_MXC_F",
			"arifle_SDAR_F",
			"arifle_TRG20_F",
			"arifle_TRG21_F",
			"arifle_TRG21_GL_F",
			"Exile_Weapon_AK107",
			"Exile_Weapon_AK107_GL",
			"Exile_Weapon_AK74",
			"Exile_Weapon_AK74_GL",
			//Apex
			"arifle_AK12_F",
			"arifle_AK12_GL_F",
			"arifle_ARX_blk_F",
			"arifle_ARX_ghex_F",
			"arifle_ARX_hex_F",
			"arifle_CTAR_blk_F",
			"arifle_CTAR_hex_F",
			"arifle_CTAR_ghex_F",
			"arifle_CTAR_GL_blk_F",
			"arifle_CTARS_blk_F",
			"arifle_CTARS_hex_F",
			"arifle_CTARS_ghex_F",
			"arifle_SPAR_01_blk_F",
			"arifle_SPAR_01_khk_F",
			"arifle_SPAR_01_snd_F",
			"arifle_SPAR_01_GL_blk_F",
			"arifle_SPAR_01_GL_khk_F",
			"arifle_SPAR_01_GL_snd_F",
			"arifle_SPAR_02_blk_F",
			"arifle_SPAR_02_khk_F",
			"arifle_SPAR_02_snd_F",
			"arifle_SPAR_03_blk_F",
			"arifle_SPAR_03_khk_F",
			"arifle_SPAR_03_snd_F",
			"arifle_MX_khk_F",
			"arifle_MX_GL_khk_F",
			"arifle_MXC_khk_F",
			"arifle_MXM_khk_F",
			"HLC_Rifle_g3ka4_GL",
			"hlc_barrel_carbine",
			"hlc_barrel_hbar",
			"hlc_barrel_standard",
			"hlc_rifle_Bushmaster300",
			"hlc_rifle_Colt727",
			"hlc_rifle_Colt727_GL",
			"hlc_rifle_FAL5000",
			"hlc_rifle_FAL5000Rail",
			"hlc_rifle_FAL5000_RH",
			"hlc_rifle_FAL5061",
			"hlc_rifle_FAL5061Rail",
			"hlc_rifle_G36A1",
			"hlc_rifle_G36A1AG36",
			"hlc_rifle_G36C",
			"hlc_rifle_G36CMLIC",
			"hlc_rifle_G36CTAC",
			"hlc_rifle_G36CV",
			"hlc_rifle_G36E1",
			"hlc_rifle_G36E1AG36",
			"hlc_rifle_G36KA1",
			"hlc_rifle_G36KE1",
			"hlc_rifle_G36KMLIC",
			"hlc_rifle_G36KTAC",
			"hlc_rifle_G36KV",
			"hlc_rifle_G36MLIAG36",
			"hlc_rifle_G36MLIC",
			"hlc_rifle_G36TAC",
			"hlc_rifle_G36V",
			"hlc_rifle_G36VAG36",
			"hlc_rifle_LAR",
			"hlc_rifle_M14DMR",
			"hlc_rifle_M21",
			"hlc_rifle_MG36",
			"hlc_rifle_RK62",
			"hlc_rifle_RU556",
			"hlc_rifle_RU5562",
			"hlc_rifle_SAMR",
			"hlc_rifle_SLR",
			"hlc_rifle_SLRchopmod",
			"hlc_rifle_STG58F",
			"hlc_rifle_STGW57",
			"hlc_rifle_aek971",
			"hlc_rifle_aek971_mtk",
			"hlc_rifle_ak12",
			"hlc_rifle_ak12gl",
			"hlc_rifle_ak74",
			"hlc_rifle_ak74_MTK",
			"hlc_rifle_ak74_dirty",
			"hlc_rifle_ak74_dirty2",
			"hlc_rifle_ak74m",
			"hlc_rifle_ak74m_MTK",
			"hlc_rifle_ak74m_gl",
			"hlc_rifle_akmgl",
			"hlc_rifle_aku12",
			"hlc_rifle_amt",
			"hlc_rifle_aug",
			"hlc_rifle_auga1_B",
			"hlc_rifle_auga1_t",
			"hlc_rifle_auga1carb",
			"hlc_rifle_auga1carb_b",
			"hlc_rifle_auga1carb_t",
			"hlc_rifle_auga2",
			"hlc_rifle_auga2_b",
			"hlc_rifle_auga2_t",
			"hlc_rifle_auga2carb",
			"hlc_rifle_auga2carb_b",
			"hlc_rifle_auga2carb_t",
			"hlc_rifle_auga2lsw",
			"hlc_rifle_auga2lsw_b",
			"hlc_rifle_auga2lsw_t",
			"hlc_rifle_auga3",
			"hlc_rifle_auga3_GL",
			"hlc_rifle_auga3_GL_B",
			"hlc_rifle_auga3_GL_BL",
			"hlc_rifle_auga3_b",
			"hlc_rifle_auga3_bl",
			"hlc_rifle_aughbar",
			"hlc_rifle_aughbar_b",
			"hlc_rifle_aughbar_t",
			"hlc_rifle_augsr",
			"hlc_rifle_augsr_b",
			"hlc_rifle_augsr_t",
			"hlc_rifle_augsrcarb",
			"hlc_rifle_augsrcarb_b",
			"hlc_rifle_augsrcarb_t",
			"hlc_rifle_augsrhbar",
			"hlc_rifle_augsrhbar_b",
			"hlc_rifle_augsrhbar_t",
			"hlc_rifle_bcmblackjack",
			"hlc_rifle_bcmjack",
			"hlc_rifle_c1A1",
			"hlc_rifle_falosw",
			"hlc_rifle_g3a3",
			"hlc_rifle_g3a3ris",
			"hlc_rifle_g3a3v",
			"hlc_rifle_g3ka4",
			"hlc_rifle_g3sg1",
			"hlc_rifle_hk33a2",
			"hlc_rifle_hk33a2RIS",
			"hlc_rifle_hk51",
			"hlc_rifle_hk53",
			"hlc_rifle_hk53RAS",
			"hlc_rifle_honeybadger",
			"hlc_rifle_l1a1slr",
			"hlc_rifle_m14sopmod",
			"hlc_rifle_osw_GL",
			"hlc_rifle_rpk74n",
			"hlc_rifle_sig5104",
			"hlc_rifle_slr107u",
			"hlc_rifle_slr107u_MTK",
			"hlc_rifle_stgw57_RIS",
			"hlc_rifle_stgw57_commando",
			"hlc_rifle_vendimus",
			"rhs_weap_m4",
			"rhs_weap_m4_grip2",
			"rhs_weap_m4_carryhandle",
			"rhs_weap_m4_carryhandle_pmag",
			"rhs_weap_m4_grip",
			"rhs_weap_m4_m203",
			"rhs_weap_m4_m320",
			"rhs_weap_m4a1_carryhandle",
			"rhs_weap_m4a1_carryhandle_grip2",
			"rhs_weap_m4a1_carryhandle_pmag",
			"rhs_weap_m4a1_carryhandle_m203",
			"rhs_weap_m4a1",
			"rhs_weap_m4a1_grip2",
			"rhs_weap_m4a1_grip",
			"rhs_weap_m4a1_m203",
			"rhs_weap_m4a1_m320",
			"rhs_weap_m4a1_blockII",
			"rhs_weap_m4a1_blockII_KAC",
			"rhs_weap_m4a1_blockII_grip2",
			"rhs_weap_m4a1_blockII_grip2_KAC",
			"rhs_weap_m4a1_blockII_M203",
			"rhs_weap_mk18",
			"rhs_weap_mk18_KAC",
			"rhs_weap_mk18_grip2",
			"rhs_weap_mk18_grip2_KAC",
			"rhs_weap_mk18_m320",
			"rhs_weap_ak103",
			"rhs_weap_ak103_npz",
			"rhs_weap_ak103_1",
			"rhs_weap_ak74m",
			"rhs_weap_ak74m_2mag",
			"rhs_weap_ak74m_2mag_camo",
			"rhs_weap_ak74m_2mag_npz",
			"rhs_weap_ak74m_camo",
			"rhs_weap_ak74m_desert",
			"rhs_weap_ak74m_desert_npz",
			"rhs_weap_ak74m_desert_folded",
			"rhs_weap_ak74m_plummag_folded",
			"rhs_weap_ak74m_folded",
			"rhs_weap_ak74m_camo_folded",
			"rhs_weap_ak74m_gp25",
			"rhs_weap_ak74m_gp25_npz",
			"rhs_weap_ak74m_npz",
			"rhs_weap_ak74m_plummag",
			"rhs_weap_ak74m_plummag_npz",
			"CSW_FNC2000",
			"CSW_FNC",
			"CSW_LVOA_C_Black",
			"CSW_LVOA_C_Sand",
			"CSW_LVOA_C_Green",
			"CSW_LVOA_C_Block",
			"CSW_LVOA_C_Black_TOB",
			"CSW_LVOA_C_Sand_TOB",
			"CSW_LVOA_C_Green_TOB",
			"CSW_LVOA_C_Block_TOB",
			"CUP_arifle_Mk16_CQC",
            "CUP_arifle_xm8_SAW",
            "CUP_arifle_xm8_sharpshooter",
            "CUP_arifle_Mk16_CQC_FG",
            "CUP_arifle_Mk16_CQC_SFG",
            "CUP_arifle_Mk16_CQC_EGLM",
            "CUP_arifle_Mk16_STD",
            "CUP_arifle_Mk16_STD_FG",
            "CUP_arifle_Mk16_STD_SFG",
            "CUP_arifle_Mk16_STD_EGLM",
            "CUP_arifle_Mk16_SV",
            "CUP_arifle_Mk17_CQC",
            "CUP_arifle_Mk17_CQC_FG",
            "CUP_arifle_Mk17_CQC_SFG",
            "CUP_arifle_Mk17_CQC_EGLM",
            "CUP_arifle_Mk17_STD",
            "CUP_arifle_Mk17_STD_FG",
            "CUP_arifle_Mk17_STD_SFG",
            "CUP_arifle_Mk17_STD_EGLM",
			"CUP_srifle_Mk12SPR",
            "CUP_srifle_M40A3",
            "CUP_srifle_M107_Base",
			"CUP_srifle_M110",
			"CUP_srifle_M24_des",
            "CUP_srifle_M24_wdl",
			"CUP_srifle_AS50"
		};
	};

	class SubMachineGuns
	{
		name = "Sub Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"hgun_PDW2000_F",
			"SMG_01_F",
			"SMG_02_F",
			"SMG_05_F",
			"hlc_smg_9mmar",
			"hlc_smg_MP5N",
			"hlc_smg_mp510",
			"hlc_smg_mp5a2",
			"hlc_smg_mp5a3",
			"hlc_smg_mp5a4",
			"hlc_smg_mp5k",
			"hlc_smg_mp5k_PDW",
			"hlc_smg_mp5sd5",
			"hlc_smg_mp5sd6",
			"rhsusf_weap_MP7A2",
			"rhsusf_weap_MP7A2_desert",
			"rhsusf_weap_MP7A2_aor1",
			"rhsusf_weap_MP7A2_winter",
			"CUP_smg_bizon"

		};
	};

	class Shotguns
	{
		name = "Shotguns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Weapon_M1014",
			"CSW_M870",
            "CUP_sgun_AA12",
            "CUP_sgun_Saiga12K"
		};
	};

	class LightMachineGuns
	{
		name = "Light Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"LMG_Mk200_F",
			"LMG_Zafir_F",
			"LMG_03_F",
			"Exile_Weapon_RPK",
			"Exile_Weapon_PK",
			"Exile_Weapon_PKP",
			"hlc_lmg_M249E2",
			"hlc_lmg_M249E2",
			"hlc_lmg_M60E4",
			"hlc_lmg_MG3KWS_b",
			"hlc_lmg_MG3KWS_g",
			"hlc_lmg_MG42",
			"hlc_lmg_MG42KWS_t",
			"hlc_lmg_m249para",
			"hlc_lmg_m249para",
			"hlc_lmg_m60",
			"hlc_lmg_mg42kws_b",
			"hlc_lmg_mg42kws_g",
			"hlc_lmg_minimi",
			"hlc_lmg_minimi_railed",
			"hlc_lmg_minimipara",
			"hlc_lmg_mk48",
			"hlc_m249_pip1",
			"hlc_m249_pip2",
			"hlc_m249_pip3",
			"hlc_m249_pip4",
			"hlc_rifle_rpk",
			"hlc_rifle_rpk12",
			"hlc_rifle_rpk74n",
			"rhs_weap_m249_pip_L",
			"rhs_weap_m249_pip_L_para",
			"rhs_weap_m249_pip_L_vfg",
			"rhs_weap_m249_pip_S",
			"rhs_weap_m249_pip_S_para",
			"rhs_weap_m249_pip_S_vfg",
			"rhs_weap_m240B",
			"rhs_weap_m240B_CAP",
			"rhs_weap_m240G",
			"rhs_weap_pkm",
			"rhs_weap_pkp"

			/*
			"MMG_01_hex_F",
			"MMG_01_tan_F",
			"MMG_02_black_F",
			"MMG_02_camo_F",
			"MMG_02_sand_F"
			*/
		};
	};

	class SniperRifles
	{
		name = "Sniper Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"arifle_MXM_Black_F",
			"arifle_MXM_F",
			"srifle_DMR_01_F",
			"srifle_DMR_02_camo_F",
			"srifle_DMR_02_F",
			"srifle_DMR_02_sniper_F",
			"srifle_DMR_03_F",
			"srifle_DMR_03_khaki_F",
			"srifle_DMR_03_multicam_F",
			"srifle_DMR_03_tan_F",
			"srifle_DMR_03_woodland_F",
			"srifle_DMR_04_F",
			"srifle_DMR_04_Tan_F",
			"srifle_DMR_05_blk_F",
			"srifle_DMR_05_hex_F",
			"srifle_DMR_05_tan_f",
			"srifle_DMR_06_camo_F",
			"srifle_DMR_06_olive_F",
			"srifle_EBR_F",
			"srifle_GM6_camo_F",
			"srifle_GM6_F",
			"srifle_LRR_camo_F",
			"srifle_LRR_F",
			"Exile_Weapon_CZ550",
			"Exile_Weapon_SVD",
			"Exile_Weapon_SVDCamo",
			"Exile_Weapon_VSSVintorez",
			"Exile_Weapon_DMR",
			//Apex
			"srifle_LRR_tna_F",
			"srifle_GM6_ghex_F",
			"srifle_DMR_07_blk_F",
			"srifle_DMR_07_hex_F",
			"srifle_DMR_07_ghex_F",
			"Exile_Weapon_m107",
			"Exile_Weapon_ksvk",
			"hlc_rifle_M1903A1OMR",
			"hlc_rifle_M1903A1_unertl",
			"hlc_rifle_PSG1A1_RIS",
			"hlc_rifle_awMagnum_BL_ghillie",
			"hlc_rifle_awMagnum_FDE_ghillie",
			"hlc_rifle_awMagnum_OD_ghillie",
			"hlc_rifle_awcovert",
			"hlc_rifle_awcovert_BL",
			"hlc_rifle_awcovert_FDE",
			"hlc_rifle_awmagnum",
			"hlc_rifle_awmagnum_BL",
			"hlc_rifle_awmagnum_FDE",
			"hlc_rifle_psg1",
			"hlc_rifle_psg1A1",
			"rhs_weap_sr25",
			"rhs_weap_sr25_ec",
			"rhs_weap_m14ebrri",
			"rhs_weap_XM2010",
			"rhs_weap_XM2010_wd",
			"rhs_weap_XM2010_d",
			"rhs_weap_XM2010_sa",
			"rhs_weap_m24sws",
			"rhs_weap_m24sws_blk",
			"rhs_weap_m24sws_ghillie",
			"rhs_weap_m40a5",
			"rhs_weap_m40a5_d",
			"rhs_weap_m40a5_w",
			"rhs_weap_M107",
			"rhs_weap_M107_d",
			"rhs_weap_M107_w",
			"rhs_weap_m110",
			"rhs_weap_sr25_ec_d",
			"rhs_weap_sr25_ec_wd"
		};
	};

	class Pistols
	{
		name = "Pistols";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] =
		{
			"hgun_ACPC2_F",
			"hgun_Pistol_heavy_01_F",
			"hgun_Pistol_heavy_02_F",
			"rhs_weap_pya",
			"hlc_smg_mp5k",
			"rhsusf_weap_m9",
			"bwa3_mp7",
			"rhs_weap_pp2000_folded",
			"rhs_weap_pb_6p9",
			"hlc_pistol_P226WestGerman",
			"hlc_pistol_mk25d",
			"hlc_pistol_p226r",
			"hlc_pistol_p226r_elite",
			"hlc_pistol_p229r",
			"hlc_pistol_p229r_elite"

		};
	};
	
	class Ammunition
	{
		name = "Ammunition";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\CargoMag_ca.paa";
		items[] =
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag_Tracer",
			"10Rnd_127x54_Mag",
			"10Rnd_338_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_93x64_DMR_05_Mag",
			"11Rnd_45ACP_Mag",
			//"130Rnd_338_Mag", SPMG
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box_Tracer",
			//"150Rnd_93x64_Mag", // NAVID
			"16Rnd_9x21_Mag",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box_Tracer",
			"20Rnd_556x45_UW_mag",
			"20Rnd_762x51_Mag",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01_tracer_green",
			"30Rnd_45ACP_Mag_SMG_01_Tracer_Red",
			"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Green",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green_mag_Tracer",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Yellow_Mag",
			"30Rnd_9x21_Green_Mag",
			"30Rnd_9x21_Red_Mag",
			"5Rnd_127x108_APDS_Mag",
			"5Rnd_127x108_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_GreenSignal_F",
			"6Rnd_RedSignal_F",
			"7Rnd_408_Mag",
			"9Rnd_45ACP_Mag",
			"Exile_Magazine_30Rnd_762x39_AK",
			"Exile_Magazine_30Rnd_545x39_AK_Green",
			"Exile_Magazine_30Rnd_545x39_AK_Red",
			"Exile_Magazine_30Rnd_545x39_AK_White",
			"Exile_Magazine_30Rnd_545x39_AK_Yellow",
			"Exile_Magazine_45Rnd_545x39_RPK_Green",
			"Exile_Magazine_75Rnd_545x39_RPK_Green",
			"Exile_Magazine_20Rnd_762x51_DMR",
			"Exile_Magazine_20Rnd_762x51_DMR_Yellow",
			"Exile_Magazine_20Rnd_762x51_DMR_Red",
			"Exile_Magazine_20Rnd_762x51_DMR_Green",
			"Exile_Magazine_10Rnd_303",
			"Exile_Magazine_100Rnd_762x54_PK_Green",
			"Exile_Magazine_7Rnd_45ACP",
			"Exile_Magazine_8Rnd_9x18",
			"Exile_Magazine_30Rnd_545x39_AK",
			"Exile_Magazine_6Rnd_45ACP",
			"Exile_Magazine_5Rnd_22LR",
			"Exile_Magazine_10Rnd_762x54",
			"Exile_Magazine_10Rnd_9x39",
			"Exile_Magazine_20Rnd_9x39",
			//"Exile_Magazine_8Rnd_74Pellets",
			"Exile_Magazine_8Rnd_74Slug",
			//Apex
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Red",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Yellow",
			"30Rnd_9x21_Mag_SMG_02_Tracer_Green",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_Tracer_F",
			"20Rnd_650x39_Cased_Mag_F",
			"10Rnd_50BW_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_Tracer_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_Green_F",
			"30Rnd_762x39_Mag_Tracer_F",
			"30Rnd_762x39_Mag_Tracer_Green_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_Green_F",
			"30Rnd_545x39_Mag_Tracer_F",
			"30Rnd_545x39_Mag_Tracer_Green_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_Red_F",
			"200Rnd_556x45_Box_Tracer_F",
			"200Rnd_556x45_Box_Tracer_Red_F",
			"10Rnd_9x21_Mag",
			"Exile_Magazine_5Rnd_127x108_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_APDS_Bullet_Cam_Mag",
			"Exile_Magazine_10Rnd_93x64_DMR_05_Bullet_Cam_Mag",
			"Exile_Magazine_7Rnd_408_Bullet_Cam_Mag",
			"Exile_Magazine_10Rnd_338_Bullet_Cam_Mag",
			"Exile_Magazine_10Rnd_127x99_m107_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_KSVK_Bullet_Cam_Mag",
			"Exile_Magazine_5Rnd_127x108_APDS_KSVK_Bullet_Cam_Mag",
			"Exile_Magazine_10Rnd_765x17_SA61",
			"Exile_Magazine_20Rnd_765x17_SA61",
			"Exile_Magazine_10Rnd_127x99_m107",
			"Exile_Magazine_5Rnd_127x108_APDS_KSVK",
			"Exile_Magazine_5Rnd_127x108_KSVK",
			"29rnd_300BLK_STANAG",
			"29rnd_300BLK_STANAG_S",
			"29rnd_300BLK_STANAG_T",
			"hlc_100Rnd_762x51_B_M60E4",
			"hlc_100Rnd_762x51_B_MG3",
			"hlc_100Rnd_762x51_Barrier_M60E4",
			"hlc_100Rnd_762x51_Barrier_MG3",
			"hlc_100Rnd_762x51_M_M60E4",
			"hlc_100Rnd_762x51_M_MG3",
			"hlc_100Rnd_762x51_Mdim_M60E4",
			"hlc_100Rnd_762x51_T_M60E4",
			"hlc_100Rnd_762x51_T_MG3",
			"hlc_100Rnd_792x57_AP_MG42",
			"hlc_100Rnd_792x57_B_MG42",
			"hlc_100Rnd_792x57_M_MG42",
			"hlc_100Rnd_792x57_T_MG42",
			"hlc_100rnd_556x45_EPR_G36",
			"hlc_10Rnd_303_AP_enfield",
			"hlc_10Rnd_303_B_enfield",
			"hlc_10Rnd_303_T_enfield",
			"hlc_10Rnd_45ACP_B_hk45",
			"hlc_10rnd_12g_buck_S12",
			"hlc_10rnd_12g_slug_S12",
			"hlc_12Rnd_45ACP_B_mk23",
			"hlc_12Rnd_45ACP_S_mk23",
			"hlc_12Rnd_45ACP_T_mk23",
			"hlc_200Rnd_792x57_AP_MG42",
			"hlc_200Rnd_792x57_B_MG42",
			"hlc_200Rnd_792x57_M_MG42",
			"hlc_200Rnd_792x57_T_MG42",
			"hlc_200rnd_556x45_B_SAW",
			"hlc_200rnd_556x45_M_SAW",
			"hlc_200rnd_556x45_Mdim_SAW",
			"hlc_200rnd_556x45_T_SAW",
			"hlc_20Rnd_762x51_B_M14",
			"hlc_20Rnd_762x51_B_fal",
			"hlc_20Rnd_762x51_Mdim_M14",
			"hlc_20Rnd_762x51_S_M14",
			"hlc_20Rnd_762x51_S_fal",
			"hlc_20Rnd_762x51_TDim_fal",
			"hlc_20Rnd_762x51_T_M14",
			"hlc_20Rnd_762x51_T_amt",
			"hlc_20Rnd_762x51_T_fal",
			"hlc_20Rnd_762x51_Tdim_M14",
			"hlc_20Rnd_762x51_b_amt",
			"hlc_20Rnd_762x51_barrier_M14",
			"hlc_20Rnd_762x51_barrier_fal",
			"hlc_20Rnd_762x51_bball_amt",
			"hlc_20Rnd_762x51_mk316_M14",
			"hlc_20Rnd_762x51_mk316_amt",
			"hlc_20Rnd_762x51_mk316_fal",
			"hlc_20rnd_762x51_IRDim_G3",
			"hlc_20rnd_762x51_MDim_G3",
			"hlc_20rnd_762x51_Mk316_G3",
			"hlc_20rnd_762x51_S_G3",
			"hlc_20rnd_762x51_T_G3",
			"hlc_20rnd_762x51_b_G3",
			"hlc_20rnd_762x51_barrier_G3",
			"hlc_24Rnd_75x55_B_stgw",
			"hlc_24Rnd_75x55_T_stgw",
			"hlc_24Rnd_75x55_ap_stgw",
			"hlc_250Rnd_762x51_B_MG3",
			"hlc_250Rnd_762x51_Barrier_MG3",
			"hlc_250Rnd_762x51_M_MG3",
			"hlc_250Rnd_762x51_T_MG3",
			"hlc_25Rnd_9x19mm_JHP_AUG",
			"hlc_25Rnd_9x19mm_M882_AUG",
			"hlc_25Rnd_9x19mm_subsonic_AUG",
			"hlc_30Rnd_10mm_B_MP5",
			"hlc_30Rnd_10mm_JHP_MP5",
			"hlc_30Rnd_303_AP_bren",
			"hlc_30Rnd_303_B_bren",
			"hlc_30Rnd_303_T_bren",
			"hlc_30Rnd_545x39_B_AK",
			"hlc_30Rnd_545x39_EP_ak",
			"hlc_30Rnd_545x39_S_AK",
			"hlc_30Rnd_545x39_t_ak",
			"hlc_30Rnd_556x45_B_AUG",
			"hlc_30Rnd_556x45_MDIM_AUG",
			"hlc_30Rnd_556x45_SOST_AUG",
			"hlc_30Rnd_556x45_SPR_AUG",
			"hlc_30Rnd_556x45_TDIM_AUG",
			"hlc_30Rnd_556x45_T_AUG",
			"hlc_30Rnd_762x39_b_ak",
			"hlc_30Rnd_762x39_t_ak",
			"hlc_30Rnd_9x19_B_MP5",
			"hlc_30Rnd_9x19_GD_MP5",
			"hlc_30Rnd_9x19_SD_MP5",
			"hlc_30rnd_556x45_EPR",
			"hlc_30rnd_556x45_EPR_G36",
			"hlc_30rnd_556x45_EPR_HK33",
			"hlc_30rnd_556x45_MDIM_G36",
			"hlc_30rnd_556x45_MDim",
			"hlc_30rnd_556x45_S",
			"hlc_30rnd_556x45_SOST",
			"hlc_30rnd_556x45_SOST_G36",
			"hlc_30rnd_556x45_SOST_HK33",
			"hlc_30rnd_556x45_SPR",
			"hlc_30rnd_556x45_SPR_G36",
			"hlc_30rnd_556x45_TDIM_G36",
			"hlc_30rnd_556x45_TDim",
			"hlc_30rnd_556x45_Tracers_G36",
			"hlc_30rnd_556x45_b_HK33",
			"hlc_30rnd_556x45_mdim_HK33",
			"hlc_30rnd_556x45_t_HK33",
			"hlc_30rnd_556x45_tdim_HK33",
			"hlc_30rnd_762x39_s_ak",
			"hlc_32rnd_9x19_B_sten",
			"hlc_40Rnd_556x45_B_AUG",
			"hlc_40Rnd_556x45_SOST_AUG",
			"hlc_40Rnd_556x45_SPR_AUG",
			"hlc_40Rnd_556x45_TDIM_AUG",
			"hlc_45Rnd_545x39_t_rpk",
			"hlc_45Rnd_762x39_m_rpk",
			"hlc_45Rnd_762x39_t_rpk",
			"hlc_500rnd_762x51_Belt",
			"hlc_500rnd_762x51_Cinematic",
			"hlc_50Rnd_44mag_B_deagle",
			"hlc_50Rnd_45ACP_B_1921",
			"hlc_50Rnd_45ACP_T_1921",
			"hlc_50Rnd_57x28_FMJ_P90",
			"hlc_50Rnd_57x28_JHP_P90",
			"hlc_50Rnd_762x51_B_M14",
			"hlc_50Rnd_762x51_B_MG3",
			"hlc_50Rnd_762x51_Barrier_MG3",
			"hlc_50Rnd_762x51_M_MG3",
			"hlc_50Rnd_762x51_T_MG3",
			"hlc_50Rnd_792x57_AP_MG42",
			"hlc_50Rnd_792x57_B_MG42",
			"hlc_50Rnd_792x57_M_MG42",
			"hlc_50Rnd_792x57_T_MG42",
			"hlc_50rnd_556x45_EPR",
			"hlc_50rnd_762x51_MDIM_G3",
			"hlc_50rnd_762x51_M_FAL",
			"hlc_50rnd_762x51_M_G3",
			"hlc_50rnd_9x19_B_9mmar",
			"hlc_5Rnd_12G_Buck_Trench",
			"hlc_5Rnd_12G_DISTRACTION_Trench",
			"hlc_5Rnd_12G_Slug_Trench",
			"rhsgref_5Rnd_792x57_kar98k",
			"hlc_5rnd_3006_1903",
			"hlc_5rnd_300WM_AP_AWM",
			"hlc_5rnd_300WM_BTSP_AWM",
			"hlc_5rnd_300WM_FMJ_AWM",
			"hlc_5rnd_300WM_SBT_AWM",
			"hlc_5rnd_300WM_T_AWM",
			"hlc_5rnd_300WM_mk248_AWM",
			"hlc_60Rnd_545x39_t_rpk",
			"hlc_6Rnd_735_B_Carcano",
			"hlc_6Rnd_735_T_Carcano",
			"hlc_75Rnd_762x39_m_rpk",
			"hlc_8Rnd_44mag_B_deagle",
			"hlc_8Rnd_44mag_JHP_deagle",
			"hlc_8Rnd_45ACP_B_hk45",
			"hlc_8Rnd_45ACP_T_hk45",
			"hlc_GRD_Red",
			"hlc_GRD_White",
			"hlc_GRD_blue",
			"hlc_GRD_green",
			"hlc_GRD_orange",
			"hlc_GRD_purple",
			"hlc_GRD_yellow",
			"hlc_VOG25_AK",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_9x18_12_57N181S",
			"rhs_mag_9x19_17",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk262_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow",
			"rhs_200rnd_556x45_M_SAW",
			"rhs_200rnd_556x45_B_SAW",
			"rhs_200rnd_556x45_T_SAW",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51_m993",
			"rhsusf_50Rnd_762x51_m80a1epr",
			"rhsusf_100Rnd_762x51",
			"rhsusf_100Rnd_762x51_m993",
			"rhsusf_100Rnd_762x51_m80a1epr",
			"rhsusf_8Rnd_00Buck",
			"rhsusf_8Rnd_Slug",
			"rhsusf_20Rnd_762x51_m993_Mag",
			"rhsusf_5Rnd_300winmag_xm2010",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm_tracer",
			"rhs_30Rnd_762x39mm_89",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK_no_tracers",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N22_AK",
			"rhs_30Rnd_545x39_AK_green",
			"rhs_45Rnd_545X39_AK",
			"rhs_45Rnd_545X39_7N10_AK",
			"rhs_45Rnd_545X39_7N22_AK",
			"rhs_45Rnd_545X39_AK_Green",
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR_green",
			"rhs_10Rnd_762x54mmR_7N1",
			"CSW_7Rnd_127x33_AE",
			"CSW_5Rnd_127x41_Magnum",
			"CSW_M870_8Rnd_buck",
			"CSW_M870_8Rnd_slug",
			"CSW_20Rnd_57x28_SS190",
			"CSW_20Rnd_57x28_SS198",
			"CSW_Taser_Probe_Mag",
			"rhsgref_5Rnd_792x57_kar98k",
 			"rhsgref_30rnd_556x45_m21",
 			"rhsgref_5Rnd_762x54_m38",
 			"rhsgref_10Rnd_792x57_m76",
			"rhssaf_30rnd_556x45_EPR_G36",
			"rhssaf_30rnd_556x45_SOST_G36",
			"rhssaf_100rnd_556x45_EPR_G36",
			"rhssaf_30rnd_556x45_SPR_G36",
			"rhssaf_30rnd_556x45_Tracers_G36",
			"rhssaf_30rnd_556x45_MDIM_G36",
			"rhssaf_30rnd_556x45_TDIM_G36",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_Tracer_F",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm_tracer",
			"rhs_30Rnd_762x39mm_89",
			"rhs_30Rnd_762x39mm_U",
			"rhsgref_30rnd_556x45_m21",
			"rhsgref_30rnd_556x45_m21_t",
			"rhs_100Rnd_762x54mmR",
			"rhs_100Rnd_762x54mmR_green",
			"rhssaf_250Rnd_762x54R",
			"CUP_20Rnd_B_AA12_Pellets",
            "CUP_20Rnd_B_AA12_74Slug",
            "CUP_20Rnd_B_AA12_HE",
            "CUP_8Rnd_B_Beneli_74Slug",
            "CUP_8Rnd_B_Saiga12_74Slug_M",
            "CUP_8Rnd_9x18_Makarov_M",
            "CUP_8Rnd_9x18_MakarovSD_M",
            "CUP_15Rnd_9x19_M9",
            "CUP_18Rnd_9x19_Phantom",
            "CUP_6Rnd_45ACP_M",
            "CUP_17Rnd_9x19_glock17",
            "CUP_7Rnd_45ACP_1911",
            "CUP_10Rnd_9x19_Compact",
            "CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",
            "CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
            "CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",
            "CUP_200Rnd_TE1_Red_Tracer_556x45_M249",
            "CUP_100Rnd_TE4_Green_Tracer_556x45_M249",
            "CUP_100Rnd_TE4_Red_Tracer_556x45_M249",
            "CUP_100Rnd_TE4_Yellow_Tracer_556x45_M249",
            "CUP_200Rnd_TE4_Green_Tracer_556x45_L110A1",
            "CUP_200Rnd_TE4_Red_Tracer_556x45_L110A1",
            "CUP_200Rnd_TE4_Yellow_Tracer_556x45_L110A1",
            "CUP_50Rnd_UK59_762x54R_Tracer",
            "CUP_64Rnd_9x19_Bizon_M",
            "CUP_64Rnd_Green_Tracer_9x19_Bizon_M",
            "CUP_64Rnd_Red_Tracer_9x19_Bizon_M",
            "CUP_64Rnd_White_Tracer_9x19_Bizon_M",
            "CUP_64Rnd_Yellow_Tracer_9x19_Bizon_M",
            "CUP_30Rnd_9x19_EVO",
            "CUP_30Rnd_9x19_UZI",
            "CUP_30Rnd_9x19_MP5",
            "CUP_20Rnd_B_765x17_Ball_M",
            "CUP_5Rnd_127x99_as50_M",
            "CUP_5Rnd_86x70_L115A1",
            "CUP_10Rnd_762x51_CZ750_Tracer",
            "CUP_10Rnd_762x51_CZ750",
            "CUP_10x_303_M",
            "CUP_5Rnd_762x51_M24",
            "CUP_10Rnd_127x99_m107",
            "CUP_20Rnd_762x51_B_M110",
            "CUP_20Rnd_TE1_Yellow_Tracer_762x51_M110",
            "CUP_20Rnd_TE1_Red_Tracer_762x51_M110",
            "CUP_20Rnd_TE1_Green_Tracer_762x51_M110",
            "CUP_20Rnd_TE1_White_Tracer_762x51_M110",
            "CUP_10Rnd_762x54_SVD_M",
            "CUP_10Rnd_9x39_SP5_VSS_M",
            "CUP_20Rnd_9x39_SP5_VSS_M",
            "CUP_5x_22_LR_17_HMR_M",
            "CUP_5Rnd_127x108_KSVK_M",
            "CUP_30Rnd_545x39_AK_M",
            "CUP_30Rnd_TE1_Green_Tracer_545x39_AK_M",
            "CUP_30Rnd_TE1_Red_Tracer_545x39_AK_M",
            "CUP_30Rnd_TE1_White_Tracer_545x39_AK_M",
            "CUP_30Rnd_TE1_Yellow_Tracer_545x39_AK_M",
            "CUP_75Rnd_TE4_LRT4_Green_Tracer_545x39_RPK_M",
            "CUP_30Rnd_762x39_AK47_M",
            "CUP_30Rnd_556x45_Stanag",
            "CUP_30Rnd_556x45_G36",
            "CUP_30Rnd_TE1_Red_Tracer_556x45_G36",
            "CUP_30Rnd_TE1_Green_Tracer_556x45_G36",
            "CUP_30Rnd_TE1_Yellow_Tracer_556x45_G36",
            "CUP_100Rnd_556x45_BetaCMag",
            "CUP_100Rnd_TE1_Red_Tracer_556x45_BetaCMag",
            "CUP_100Rnd_TE1_Green_Tracer_556x45_BetaCMag",
            "CUP_100Rnd_TE1_Yellow_Tracer_556x45_BetaCMag",
            "CUP_20Rnd_556x45_Stanag",
            "CUP_20Rnd_762x51_CZ805B",
            "CUP_20Rnd_TE1_Yellow_Tracer_762x51_CZ805B",
            "CUP_20Rnd_TE1_Red_Tracer_762x51_CZ805B",
            "CUP_20Rnd_TE1_Green_Tracer_762x51_CZ805B",
            "CUP_20Rnd_TE1_White_Tracer_762x51_CZ805B",
            "CUP_20Rnd_762x51_DMR",
            "CUP_20Rnd_TE1_Yellow_Tracer_762x51_DMR",
            "CUP_20Rnd_TE1_Red_Tracer_762x51_DMR",
            "CUP_20Rnd_TE1_Green_Tracer_762x51_DMR",
            "CUP_20Rnd_TE1_White_Tracer_762x51_DMR",
            "CUP_20Rnd_762x51_FNFAL_M",
            "CUP_30Rnd_Sa58_M_TracerG",
            "CUP_30Rnd_Sa58_M_TracerR",
            "CUP_30Rnd_Sa58_M_TracerY",
            "CUP_30Rnd_Sa58_M",
            "CUP_20Rnd_762x51_B_SCAR",
            "CUP_20Rnd_TE1_Yellow_Tracer_762x51_SCAR",
            "CUP_20Rnd_TE1_Red_Tracer_762x51_SCAR",
            "CUP_20Rnd_TE1_Green_Tracer_762x51_SCAR",
            "CUP_20Rnd_TE1_White_Tracer_762x51_SCAR",
			"CUP_hgun_MicroUzi"
			//"rhs_30Rnd_762x39mm"

		};
	};

	class Explosives
	{
		name = "Explosives";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargothrow_ca.paa";
		items[] =
		{
			"APERSBoundingMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSTripMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"IEDLandBig_Remote_Mag",
			"IEDLandSmall_Remote_Mag",
			"IEDUrbanBig_Remote_Mag",
			"IEDUrbanSmall_Remote_Mag",
			"SatchelCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"rhs_mine_pmn2_mag",
			"rhs_mine_tm62m_mag",
			"rhsusf_m112_mag",
			"rhsusf_m112x4_mag",
			"rhs_mine_m19_mag"
		};
	};
	
	class Grenades
	{
		name = "Grenades";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargothrow_ca.paa";
		items[] =
		{
			"HandGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"O_IR_Grenade",
			"I_IR_Grenade",
			"ACE_M14",
			"ACE_M84",
			"1Rnd_HE_Grenade_shell",
			"rhs_mag_fakel",
			"rhs_mag_m576",
			"rhs_mag_m18_green",
			"rhs_mag_m18_purple",
			"rhs_mag_m18_red",
			"rhs_mag_m18_yellow",
			"rhs_mag_m67",
			"rhs_mag_mk84",
			"rhs_mag_mk3a2",
			"rhs_mag_m4009",
			"rhs_mag_m7a3_cs",
			"rhs_mag_an_m8hc",
			"rhs_mag_an_m14_th3"
		};
	};
	
	class PointerAttachments
	{
		name = "Pointer Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"acc_pointer_IR",
			"ACE_acc_pointer_red",
			"ACE_acc_pointer_green_IR",
			"ACE_acc_pointer_green",
			"ACE_SpareBarrel",
			"acc_flashlight",
			"rhsusf_acc_anpeq15side",
			"rhsusf_acc_anpeq15",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_anpeq15_light"
		};
	};
	
	class UnderbarrelAttachments
	{
		name = "Underbarrel Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itembipod_ca.paa";
		items[] =
		{
			"bipod_01_F_blk",
			"bipod_01_F_mtp",
			"bipod_01_F_snd",
			"bipod_02_F_blk",
			"bipod_02_F_hex",
			"bipod_02_F_tan",
			"bipod_03_F_blk",
			"bipod_03_F_oli",
			"bipod_01_F_khk",
			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip2_tan",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip3_tan",
			
			// START RHS
			
			"rhsusf_acc_harris_bipod"
		};
	};

	class MuzzleAttachments
	{
		name = "Barrel Attachments";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemmuzzle_ca.paa";
		items[] =
		{
			"muzzle_snds_338_black",
			"muzzle_snds_338_green",
			"muzzle_snds_338_sand",
			"muzzle_snds_93mmg",
			"muzzle_snds_93mmg_tan",
			"muzzle_snds_acp",
			"muzzle_snds_B",
			"muzzle_snds_H",
			"muzzle_snds_H_MG",
			"muzzle_snds_H_SW",
			"muzzle_snds_L",
			"muzzle_snds_M",
			
			//Apex
			
			"muzzle_snds_H_khk_F",
			"muzzle_snds_H_snd_F",
			"muzzle_snds_58_blk_F",
			"muzzle_snds_m_khk_F",
			"muzzle_snds_m_snd_F",
			"muzzle_snds_B_khk_F",
			"muzzle_snds_B_snd_F",
			"muzzle_snds_58_wdm_F",
			"muzzle_snds_65_TI_blk_F",
			"muzzle_snds_65_TI_hex_F",
			"muzzle_snds_65_TI_ghex_F",
			"muzzle_snds_H_MG_blk_F",
			"muzzle_snds_H_MG_khk_F",
			"hlc_muzzle_300blk_KAC",
			"hlc_muzzle_545SUP_AK",
			"hlc_muzzle_556NATO_KAC",
			"hlc_muzzle_762SUP_AK",
			"hlc_muzzle_Agendasix",
			"hlc_muzzle_Agendasix10mm",
			"hlc_muzzle_Tundra",
			"hlc_muzzle_snds_AUG",
			"hlc_muzzle_snds_HK33",
			"hlc_muzzle_snds_M14",
			"hlc_muzzle_snds_a6AUG",
			"hlc_muzzle_snds_fal",
			"hlc_muzzle_snds_g3",
			
			// START RHS
			
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_rotex5_tan",
			"rhsusf_acc_nt4_black",
			"rhsusf_acc_nt4_tan",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_M2010S",
			"rhs_acc_dtk4short",
			"rhs_acc_dtk4long",
			"rhs_acc_dtk4screws",
			"rhs_acc_tgpa",
			"rhs_acc_pbs1",
			"rhs_acc_dtk3",
			"rhs_acc_dtk1",
			"rhs_acc_dtk",
			"rhs_acc_dtk1l",
			"rhs_acc_ak5",
			
			// CUP
			
            "CUP_muzzle_PBS4",
            "CUP_muzzle_PB6P9",
            "CUP_muzzle_Bizon",
            "CUP_muzzle_snds_M110",
            "CUP_muzzle_snds_M14",
            "CUP_muzzle_snds_M9",
            "CUP_muzzle_snds_MicroUzi",
            "CUP_muzzle_snds_AWM",
            "CUP_muzzle_snds_G36_black",
            "CUP_muzzle_snds_G36_desert",
            "CUP_muzzle_snds_L85",
            "CUP_muzzle_snds_M16_camo",
            "CUP_muzzle_snds_M16",
            "CUP_muzzle_snds_SCAR_L",
            "CUP_muzzle_mfsup_SCAR_L",
            "CUP_muzzle_snds_SCAR_H",
            "CUP_muzzle_mfsup_SCAR_H",
            "CUP_muzzle_snds_XM8"
		};
	};
	
	class OpticAttachments
	{
		name = "Scopes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemoptic_ca.paa";
		items[] =
		{
			"optic_Aco",
			"optic_ACO_grn",
			"optic_ACO_grn_smg",
			"optic_Aco_smg",
			"optic_AMS",
			"optic_AMS_khk",
			"optic_AMS_snd",
			"optic_Arco",
			"optic_DMS",
			"optic_Hamr",
			"optic_Holosight",
			"optic_Holosight_smg",
			"optic_KHS_blk",
			"optic_KHS_hex",
			"optic_KHS_old",
			"optic_KHS_tan",
			"optic_LRPS",
			"optic_MRCO",
			"optic_MRD",
			"optic_Nightstalker",
			"optic_NVS",
			"optic_SOS",
			//"optic_tws",
			//"optic_tws_mg",
			"optic_Yorris",
			//Apex
			"optic_Arco_blk_F",
			"optic_Arco_ghex_F",
			"optic_DMS_ghex_F",
			"optic_Hamr_khk_F",
			"optic_ERCO_blk_F",
			"optic_ERCO_khk_F",
			"optic_ERCO_snd_F",
			"optic_SOS_khk_F",
			"optic_LRPS_tna_F",
			"optic_LRPS_ghex_F",
			"optic_Holosight_blk_F",
			"optic_Holosight_khk_F",
			"optic_Holosight_smg_blk_F",
			"HLC_Optic_1p29",
			"HLC_Optic_G36Dualoptic15x",
			"HLC_Optic_G36Dualoptic15x2d",
			"HLC_Optic_G36Export15x",
			"HLC_Optic_G36Export15x2d",
			"HLC_Optic_G36Export35x",
			"HLC_Optic_G36Export35x2d",
			"HLC_Optic_G36dualoptic35x",
			"HLC_Optic_G36dualoptic35x2d",
			"HLC_Optic_PSO1",
			"HLC_Optic_ZFSG1",
			"hlc_optic_Kern",
			"hlc_optic_Kern2d",
			"hlc_optic_LRT_m14",
			"hlc_optic_PVS4FAL",
			"hlc_optic_PVS4G3",
			"hlc_optic_PVS4M14",
			"hlc_optic_accupoint_g3",
			"hlc_optic_artel_m14",
			"hlc_optic_goshawk",
			"hlc_optic_kobra",
			"hlc_optic_suit",
			
			// START RHS
			
			"rhsusf_acc_eotech_552_d",
	        "rhsusf_acc_eotech_552",
			"rhsusf_acc_eotech_xps3",
			"rhsusf_acc_EOTECH",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_pip",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG_pip",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_EOTECH",

			// Added by ElShotte - 19 Items
			"rhsusf_acc_ACOG_MDO",
			"rhsusf_acc_ACOG_RMR",
			"rhsusf_acc_ACOG_d",
			"rhsusf_acc_ACOG_wd",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_A_3d",
			"rhsusf_acc_M8541",
			"rhsusf_acc_M8541_low",
			"rhsusf_acc_M8541_low_d",
			"rhsusf_acc_M8541_low_wd"
		};
	};
	
	class AntiRadiationMasks
	{
		name = "Anti-Radiation Masks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"skn_m04_gas_mask_bare_dry",
			"skn_m04_gas_mask_blk",
			"skn_m04_gas_mask_blu",
			"skn_m04_gas_mask_gre",
			"skn_m50_gas_mask_hood",
			"skn_m50_gas_mask_hood_wd",
			"skn_m10_balaclava_blue_dry",
			"skn_m10_balaclava_red_dry",
			"skn_m10_balaclava_white_dry",
			"skn_m10_balaclava_yellow_dry"
		};
	};
	
	class AntiRadiationSuits
	{
		name = "Anti-Radiation Masks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"skn_u_nbc_indep_blk",
			"skn_u_nbc_bluf_mtp",
			"skn_u_nbc_bluf_wd",
			"skn_u_nbc_opf_blue",
			"skn_u_nbc_opf_red",
			"skn_u_nbc_opf_white",
			"skn_u_nbc_opf_yellow"
		};
	};
	


	// Vehicles

	class MikesBikes
	{
		name = "Wheelie Bois";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"C_Quadbike_01_F",
			"NDS_6x6_ATV_CIV",
			"CUP_B_M1030",
			"CUP_O_TT650_CHDKZ",
			"CUP_O_TT650_TKA",
			"CUP_C_TT650_CIV"
		};
	};

	class CivilianCars
	{
		name = "Cars";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Car_Kart_Black",
			"Exile_Car_OldTractor_Red",
			"Exile_Car_TowTractor_White",
			"Exile_Car_Tractor_Red",
			"Exile_Car_UAZ_Green",
			"Exile_Car_UAZ_Open_Green",
			"Exile_Car_Octavius_White",
			"Exile_Car_Golf_Red",
			"Exile_Car_LandRover_Green",
			"Exile_Car_LandRover_Ambulance_Green",
			"Exile_Car_Lada_Green",
			"Exile_Car_Volha_White",
			"Exile_Car_Hatchback_Rusty1",
			"Exile_Car_Hatchback_Rusty2",
			"Exile_Car_Hatchback_Rusty3",
			"Exile_Car_Hatchback_Sport_Red",
			"Exile_Car_SUV_Red",
			"Exile_Car_SUVXL_Black",
			"Exile_Car_SUV_Armed_Black",
			"Exile_Car_Offroad_Rusty1",
			"Exile_Car_Offroad_Rusty2",
			"Exile_Car_Offroad_Rusty3",
			"Exile_Car_Offroad_Repair_Civillian",
			"Exile_Car_Offroad_Armed_Guerilla01",
			"Exile_Car_BRDM2_HQ",
			"Exile_Car_BTR40_MG_Green",
			"Exile_Car_BTR40_Green",
			"Exile_Car_HMMWV_M134_Green",
			"Exile_Car_HMMWV_M2_Green",
			"Exile_Car_HMMWV_MEV_Green",
			"Exile_Car_HMMWV_UNA_Green",
			"Exile_Car_Strider",
			"Exile_Car_Hunter",
			"Exile_Car_Ifrit",
			"Exile_Car_ProwlerLight",
			"Exile_Car_ProwlerUnarmed",
			"Exile_Car_QilinUnarmed",
			"Exile_Car_MB4WD",
			"Exile_Car_MB4WDOpen",
			
			// RHS
			
			"rhsusf_rg33_d",
			"rhsusf_rg33_usmc_d"
			


		};
	};

	class CivilianTrucks
	{
		name = "Trucks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Car_Van_Black",
			"Exile_Car_Van_Box_Black",
			"Exile_Car_Van_Fuel_Black",
			"Exile_Car_Ural_Open_Worker",
			"Exile_Car_Ural_Covered_Worker",
			"Exile_Car_V3S_Covered",
			"Exile_Car_Zamak",
			"Exile_Car_Tempest",
			"Exile_Car_HEMMT",
			"Exile_Car_Ikarus_Blue",
			"RHS_UAZ_MSV_01",
			"rhs_uaz_open_MSV_01",
			"rhs_uaz_vdv",
			"RHS_Ural_Open_Civ_01",
			"RHS_Ural_Open_Civ_02",
			"RHS_Ural_Open_Civ_03",
			"RHS_Ural_MSV_01",
			"RHS_Ural_Fuel_MSV_01",
			"RHS_Ural_Open_MSV_01",
			"rhs_Ural_Flat_MSV_01",
			"CUP_O_Ural_CHDKZ",
			"CUP_O_Ural_Empty_CHDKZ",
			"CUP_O_Ural_Empty_SLA",
			"CUP_O_Ural_Empty_TKA",
			"CUP_O_Ural_Open_CHDKZ",
			"CUP_O_Ural_Open_SLA",
			"CUP_O_Ural_Open_TKA",
			"CUP_O_Ural_Refuel_CHDKZ",
			"CUP_O_Ural_Refuel_SLA",
			"CUP_O_Ural_Refuel_TKA",
			"CUP_O_Ural_Repair_CHDKZ",
			"CUP_O_Ural_Repair_SLA",
			"CUP_O_Ural_Repair_TKA",
			"CUP_O_Ural_SLA",
			"CUP_O_Ural_TKA",
			"CUP_C_Datsun",
			"CUP_C_Datsun_4seat",
			"CUP_C_Datsun_Covered",
			"CUP_C_Datsun_Plain",
			"CUP_C_Datsun_Tubeframe",
			"CUP_C_LR_Transport_CTK",
			"CUP_C_UAZ_Unarmed_TK_CIV",
			"CUP_C_Ural_Civ_01",
			"CUP_C_Ural_Civ_02",
			"CUP_C_Ural_Civ_03",
			"CUP_C_Ural_Open_Civ_01",
			"CUP_C_Ural_Open_Civ_02",
			"CUP_C_Ural_Open_Civ_03"
		};
	};

	class MilitaryChoppers
	{
		name = "Military Helicopters";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"RHS_CH_47F",
			"rhs_CH_47F_10",
			"rhs_ka60_c",
			"rhs_ka60_grey",
			"B_Heli_Transport_01_F",
			"RHS_UH60M",
			"rhs_UH60M_MEV2_d",
			"rhs_Mi8mt_vvs",
			"rhs_Mi8mt_cargo_vvs",
			"rhs_UH1Y_unarmed",
			"CUP_B_AH1Z_NoWeapons",
			"CUP_B_AH6J_ESCORT_USA",
			"CUP_B_AW159_Unarmed_BAF",
			"CUP_B_CH47F_GB",
			"CUP_B_CH47F_USA",
			"CUP_B_CH53E_GER",
			"CUP_B_CH53E_USMC",
			"CUP_B_CH53E_VIV_GER",
			"CUP_B_MH60S_FFV_USMC",
			"CUP_B_MH60S_USMC",
			"CUP_B_MH6J_USA",
			"CUP_B_MI6A_CDF",
			"CUP_B_Mi171Sh_Unarmed_ACR",
			"CUP_B_Mi17_CDF",
			"CUP_B_Mi17_medevac_CDF",
			"CUP_B_UH1Y_MEV_F",
			"CUP_B_UH1Y_UNA_F",
			"CUP_B_UH60L_FFV_US",
			"CUP_B_UH60L_US",
			"CUP_B_UH60L_Unarmed_FFV_MEV_US",
			"CUP_B_UH60L_Unarmed_FFV_US",
			"CUP_B_UH60L_Unarmed_US",
			"CUP_B_UH60M_FFV_US",
			"CUP_B_UH60M_US",
			"CUP_B_UH60M_Unarmed_FFV_MEV_US",
			"CUP_B_UH60M_Unarmed_FFV_US",
			"CUP_B_UH60M_Unarmed_US",
			"CUP_I_UH60L_FFV_RACS",
			"CUP_I_UH60L_RACS",
			"CUP_I_UH60L_Unarmed_FFV_MEV_Racs",
			"CUP_I_UH60L_Unarmed_FFV_Racs",
			"CUP_I_UH60L_Unarmed_RACS",
			"CUP_O_Mi17_TK",
			"CUP_O_Mi8_medevac_CHDKZ",
			"CUP_O_Mi8_medevac_RU"
		};
	};
	
	
	
	class CivilianChoppers
	{
		name = "Civilian Helicopters";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Chopper_Hummingbird_Green",
			"Exile_Chopper_Hummingbird_Civillian_Wasp",
			"Exile_Chopper_Huey_Green",
			"Exile_Chopper_Huey_Armed_Green",
			"Exile_Chopper_Taru_Black",
			"Exile_Chopper_Taru_Covered_Black",
			"Exile_Chopper_Taru_Transport_Black",
			"Exile_Chopper_Orca_BlackCustom",
			"Exile_Chopper_Mohawk_FIA",
			"Exile_Chopper_Huron_Black",
			"Exile_Chopper_Hellcat_Green",
			"CUP_C_Mi17_Civilian_RU"
		};
	};

	class CivilianPlanes
	{
		name = "Planes";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"Exile_Plane_Cessna",
			"Exile_Plane_AN2_Green",
			"Exile_Plane_Ceasar",
			"Exile_Plane_BlackfishInfantry",
			"Exile_Plane_BlackfishVehicle"
		};
	};

	class MilitaryTransport
	{
		name = "Military Transport";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"NDS_6x6_ATV_MIL",
			"NDS_6x6_ATV_MIL2",
			"NDS_6x6_ATV_MIL_LR",
			"NDS_6x6_ATV_MIL_LR2",
			"rhs_tigr_vdv",
			"rhs_tigr_ffv_3camo_vdv",
			"rhs_tigr_ffv_vdv",
			"rhs_tigr_m_test",
			"rhs_gaz66_r142_vmf",
			"rhs_gaz66_repair_vmf",
			"rhs_gaz66_vmf",
			"rhs_gaz66_flat_vdv",
			"rhs_gaz66o_vdv",
			"rhs_gaz66o_flat_vdv",
			"rhs_gaz66_ammo_vmf",
			"rhsusf_m1025_w",
			"rhsusf_m1025_w_m2",
			"rhsusf_m998_w_2dr",
			"rhsusf_m998_w_4dr",
			"rhsusf_m998_w_s_2dr_fulltop",
			"rhsusf_m998_d_s_2dr_fulltop",
			"rhsusf_m998_w_s_2dr_halftop",
			"rhsusf_m998_d_s_2dr_halftop",
			"rhsusf_m998_d_s_4dr_fulltop",
			"rhsusf_m998_w_s_4dr_fulltop",
			"rhsusf_m998_d_s_4dr_halftop",
			"rhsusf_m998_w_s_4dr_halftop",
			"rhsusf_M1078A1P2_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_d_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_open_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_wd_flatbed_fmtv_usarmy",
			"rhsusf_M1078A1P2_B_d_flatbed_fmtv_usarmy",
			"rhsgref_cdf_reg_uaz_ags",
 			"rhsgref_cdf_reg_uaz_dshkm",
			"rhssaf_un_ural",
			"rhssaf_un_uaz",
			"rhssaf_un_uaz_open",
			"rhssaf_army_ural",
			"rhssaf_army_ural_open",
			"rhssaf_army_ural_fuel",
			"rhssaf_army_pts",
			"rhssaf_m998_olive_2dr_halftop",
			"rhssaf_m998_olive_2dr_fulltop",
			"rhssaf_m1025_olive",
			"CUP_B_HMMWV_Transport_USA",
			"CUP_B_HMMWV_Unarmed_USA",
			"CUP_B_HMMWV_Unarmed_USMC",
			"CUP_B_LR_Transport_CZ_W",
			"CUP_B_LR_Transport_GB_W",
			"CUP_C_UAZ_Open_TK_CIV",
			"CUP_I_BTR40_TKG",
			"CUP_O_UAZ_Open_RU",
			"CUP_O_UAZ_Unarmed_RU",
			"CUP_O_Ural_Empty_RU",
			"CUP_O_Ural_Open_RU",
			"CUP_O_Ural_RU",
			"CUP_O_Ural_Refuel_RU",
			"CUP_O_Ural_Repair_RU",
			"CUP_B_HMMWV_Ambulance_ACR",
			"CUP_B_HMMWV_Ambulance_USA",
			"CUP_B_HMMWV_Ambulance_USMC",
			"CUP_B_LR_Ambulance_CZ_D",
			"CUP_B_LR_Ambulance_CZ_W",
			"CUP_B_LR_Ambulance_GB_D",
			"CUP_B_LR_Ambulance_GB_W",
			"CUP_B_LR_Transport_CZ_D",
			"CUP_B_LR_Transport_GB_D",
			"CUP_B_UAZ_Open_ACR",
			"CUP_B_UAZ_Open_CDF",
			"CUP_B_UAZ_Unarmed_ACR",
			"CUP_B_UAZ_Unarmed_CDF",
			"CUP_B_Ural_CDF",
			"CUP_B_Ural_Empty_CDF",
			"CUP_B_Ural_Open_CDF",
			"CUP_B_Ural_Refuel_CDF",
			"CUP_B_Ural_Repair_CDF"

		};
	};
	
	class MilitaryArmed
	{
		name = "Military Armed";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"CUP_BAF_Jackal2_GMG_W",
			"CUP_BAF_Jackal2_L2A1_W",
			"CUP_B_BAF_Coyote_L2A1_W",
			"CUP_B_Dingo_GER_Wdl",
			"CUP_B_FV432_Bulldog_GB_W_RWS",
			"CUP_B_HMMWV_AGS_GPK_ACR",
			"CUP_B_HMMWV_Crows_M2_USA",
			"CUP_B_HMMWV_Crows_MK19_USA",
			"CUP_B_HMMWV_DSHKM_GPK_ACR",
			"CUP_B_HMMWV_M1114_USMC",
			"CUP_B_HMMWV_M2_GPK_USA",
			"CUP_B_HMMWV_M2_USA",
			"CUP_B_HMMWV_M2_USMC",
			"CUP_B_HMMWV_MK19_USMC",
			"CUP_B_HMMWV_SOV_USA",
			"CUP_B_LAV25M240_USMC",
			"CUP_B_LAV25_HQ_USMC",
			"CUP_B_LAV25_USMC",
			"CUP_B_LR_MG_CZ_W",
			"CUP_B_LR_MG_GB_W",
			"CUP_B_LR_Special_CZ_W",
			"CUP_B_Mastiff_HMG_GB_W",
			"CUP_B_Ridgback_HMG_GB_W",
			"CUP_I_Datsun_PK_Random",
			"CUP_I_SUV_Armored_ION",
			"CUP_I_UAZ_MG_UN",
			"CUP_O_BRDM2_CHDKZ",
			"CUP_O_BRDM2_HQ_CHDKZ",
			"CUP_O_BRDM2_HQ_SLA",
			"CUP_O_BRDM2_SLA",
			"CUP_O_BTR90_HQ_RU",
			"CUP_O_BTR90_RU",
			"CUP_O_Datsun_PK_Random",
			"CUP_O_GAZ_Vodnik_PK_RU",
			"CUP_O_LR_MG_TKA",
			"CUP_O_LR_MG_TKM",
			"CUP_O_UAZ_AGS30_RU",
			"CUP_O_UAZ_MG_RU"
		};
	};


	class UAVs
	{
		name = "Unmanned Aerial Vehicles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\gps_ca.paa";
		items[] =
		{
			//"I_UavTerminal",
			//"I_UAV_01_backpack_F"
		};
	};

	class StaticMGs
	{
		name = "Static Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"O_HMG_01_support_F",
			//"O_HMG_01_support_high_F", // Does not seem to work with HMG01, only the lower version does
			"O_HMG_01_weapon_F"
		};
	};
	
	
	class ExtendedBaseMod
	{
		name = "ExtendedBaseMod";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
		// OPA extendedbase start traderlist
		"Land_HBarrier_1_F_Kit",
		"Land_HBarrier_3_F_Kit",
		"Land_HBarrier_5_F_Kit",
		"Land_BagBunker_Tower_F_Kit",
		"CamoNet_OPFOR_open_F_Kit",
		"CamoNet_INDP_open_F_Kit",
		"CamoNet_BLUFOR_open_F_Kit",
		///////////////////////// V0.0.2
		"Land_CncBarrier_F_Kit",
		"Land_Stone_4m_F_Kit",
		"Land_Stone_Gate_F_Kit",
		"PierLadder_F_Kit",
		"Land_WaterCooler_01_new_F_Kit",
		///////////////////////// V0.0.3
		"Land_Pallet_MilBoxes_F_Kit",
		"Land_Cargo20_military_green_F_Kit",
		"Land_BagFence_Corner_F_Kit",
		"Land_BagFence_Long_F_Kit",
		"Land_HBarrierTower_F_Kit",
		"Land_Metal_wooden_rack_F_Kit",
		"Land_BagBunker_Small_F_Kit",
		"Land_Bunker_F_Kit",
		"Land_HBarrierWall_corner_F_Kit",
		"Land_HBarrierWall6_F_Kit",
		"Land_HBarrierWall4_F_Kit",
		"Land_RampConcrete_F_Kit",
		///////////////////////// V0.0.4
		"Land_Wall_IndCnc_4_F_Kit",
		"Land_City2_4m_F_Kit",
		"Land_City2_8m_F_Kit",
		"Land_HelipadCivil_F_Kit",
		"Land_Rack_F_Kit",
		///////////////////////// V0.1.0
		"Land_City_Gate_F_Kit",
		"Land_BarGate_F_Kit",
		"Land_Icebox_F_Kit",
		"Land_Sign_WarningMilitaryArea_F_Kit",
		"Land_Mil_WallBig_4m_F_Kit",
		"Land_Cargo_Patrol_V2_F_Kit",
		///////////////////////// V0.1.1
		"Land_Pier_small_F_Kit",
		"Land_Wall_Tin_4_Kit",
		///////////////////////// V0.1.2
		"Land_Tank_rust_F_Kit",
		"Land_ShelvesMetal_F_Kit",
		"Land_Cargo_Tower_V2_F_Kit",
		"Land_FuelStation_Feed_F_Kit",
		"Land_BagBunker_Large_F_Kit",
		"ShootingPos_F_Kit",
		///////////////////////// V0.1.3
		"Land_cargo_house_slum_F_Kit",
		"Land_Cargo40_light_green_F_Kit",
		"Land_Cargo_House_V2_F_Kit",
		"Land_LampHalogen_F_Kit",
		///////////////////////// V0.1.4
		"Land_LampAirport_F_Kit",
		"Land_CncShelter_F_Kit",
		"Land_Wall_IndCnc_2deco_F_Kit",
		"Land_CncWall4_F_Kit",
		"Land_FuelStation_Shed_F_Kit",
		"Land_Shed_Small_F_Kit",		
		"Land_Razorwire_F_Kit",
		///////////////////////// V0.1.5
		"Land_u_Addon_01_V1_F_Kit", //brokenshed
		"Land_Cargo20_sand_F_Kit",
		"Land_GH_Stairs_F_Kit",
		"Land_i_Garage_V2_F_Kit",
		"Land_GH_Platform_F_Kit",
		"Land_TentDome_F_Kit",
		"Land_TentHangar_V1_F_Kit",
		///////////////////////// V0.1.6
		"Land_CncWall1_F_Kit",
		"Land_CncBarrierMedium_F_Kit",
		"Land_Crash_barrier_F_Kit",
		"Land_Shed_Big_F_Kit",
		"Land_TouristShelter_01_F_Kit",
		"Land_Water_source_F_Kit",
		"Land_Sign_WarningMilitaryVehicles_F_Kit",
		"Land_Sign_WarningMilAreaSmall_F_Kit",
		"Land_Concrete_SmallWall_8m_F_Kit",
		"Land_Concrete_SmallWall_4m_F_Kit",
		///////////////////////// V0.1.7
		"Land_PortableLight_double_F_Kit",
		"Land_Radar_Small_F_Kit",
		"Land_Cargo_addon02_V2_F_Kit", //Slumplane
		"Land_TableDesk_F_Kit",
		"Land_ToiletBox_F_Kit",
		"Land_Pier_Box_F_Kit"
		// OPA extendedbase end traderlist
		
		};
	};
	

};
