	class CUPUniforms
	{
		name = "CUP Uniforms";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{

			"CUP_U_B_CZ_WDL_TShirt",
			"CUP_U_B_GER_Tropentarn_1",
			"CUP_U_B_GER_Tropentarn_2",
			"CUP_U_B_GER_Ghillie",
			"CUP_U_B_GER_Flecktarn_1",
			"CUP_U_B_GER_Flecktarn_2",
			"CUP_U_B_GER_Fleck_Ghillie",
			"CUP_U_B_USMC_Officer",
			"CUP_U_B_USMC_PilotOverall",
			"CUP_U_B_USMC_Ghillie_WDL",
			"CUP_U_B_USMC_MARPAT_WDL_Sleeves",
			"CUP_U_B_USMC_MARPAT_WDL_RolledUp",
			"CUP_U_B_USMC_MARPAT_WDL_Kneepad",
			"CUP_U_B_USMC_MARPAT_WDL_TwoKneepads",
			"CUP_U_B_USMC_MARPAT_WDL_RollUpKneepad",
			"CUP_U_B_FR_SpecOps",
			"CUP_U_B_FR_Scout",
			"CUP_U_B_FR_Scout1",
			"CUP_U_B_FR_Scout2",
			"CUP_U_B_FR_Scout3",
			"CUP_U_B_FR_Officer",
			"CUP_U_B_FR_Corpsman",
			"CUP_U_B_FR_DirAction",
			"CUP_U_B_FR_DirAction2",
			"CUP_U_B_FR_Light",
			"CUP_U_I_GUE_Flecktarn",
			"CUP_U_I_GUE_Flecktarn2",
			"CUP_U_I_GUE_Flecktarn3",
			"CUP_U_I_GUE_Woodland1",
			"CUP_U_I_Ghillie_Top",
			"CUP_U_I_RACS_PilotOverall",

			"CUP_U_O_SLA_Overalls_Pilot",
			"CUP_U_O_SLA_Overalls_Tank",
			"CUP_U_O_Partisan_TTsKO",
			"CUP_U_O_Partisan_TTsKO_Mixed",
			"CUP_U_O_Partisan_VSR_Mixed1",
			"CUP_U_O_Partisan_VSR_Mixed2",
			"CUP_U_O_TK_Officer",
			"CUP_U_O_TK_MixedCamo",
			"CUP_U_O_TK_Green",
			"CUP_U_O_TK_Ghillie",
			"CUP_U_O_TK_Ghillie_Top",
			"CUP_U_B_BAF_DDPM_S1_RolledUp",
			"CUP_U_B_BAF_DDPM_S1_UnRolled",
			"CUP_U_B_BAF_DDPM_Tshirt",
			"CUP_U_B_BAF_DPM_S1_RolledUp",
			"CUP_U_B_BAF_DPM_S2_UnRolled",
			"CUP_U_B_BAF_DPM_Tshirt",
			"CUP_U_B_BAF_MTP_S1_RolledUp",
			"CUP_U_B_BAF_MTP_S2_UnRolled",
			"CUP_U_B_BAF_MTP_Tshirt",
			"CUP_U_B_BAF_MTP_S3_RolledUp",
			"CUP_U_B_BAF_MTP_S4_UnRolled",
			"CUP_U_B_BAF_MTP_S5_UnRolled",
			"CUP_U_B_BAF_MTP_S6_UnRolled"

		};
	};
	class CUPHeadgear
	{
		name = "CUP Headgear";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"CUP_H_BAF_Helmet_1_DDPM",
			"CUP_H_BAF_Helmet_1_DPM",
			"CUP_H_BAF_Helmet_1_MTP",
			"CUP_H_BAF_Helmet_2_DDPM",
			"CUP_H_BAF_Helmet_2_DPM",
			"CUP_H_BAF_Helmet_2_MTP",
			"CUP_H_BAF_Helmet_3_DDPM",
			"CUP_H_BAF_Helmet_3_DPM",
			"CUP_H_BAF_Helmet_3_MTP",
			"CUP_H_BAF_Helmet_4_DDPM",
			"CUP_H_BAF_Helmet_4_DPM",
			"CUP_H_BAF_Helmet_4_MTP",
			"CUP_H_BAF_Officer_Beret_PRR_O",
			"CUP_H_C_Beret_01",
			"CUP_H_C_Beret_02",
			"CUP_H_C_Beret_03",
			"CUP_H_C_Beret_04",
			"CUP_H_C_Ushanka_01",
			"CUP_H_C_Ushanka_02",
			"CUP_H_C_Ushanka_03",
			"CUP_H_C_Ushanka_04",
			"CUP_H_FR_BandanaGreen",
			"CUP_H_FR_BandanaWdl",
			"CUP_H_FR_Bandana_Headset",
			"CUP_H_FR_BeanieGreen",
			"CUP_H_FR_BoonieMARPAT",
			"CUP_H_FR_BoonieWDL",
			"CUP_H_FR_Cap_Headset_Green",
			"CUP_H_FR_Cap_Officer_Headset",
			"CUP_H_FR_ECH",
			"CUP_H_FR_Headband_Headset",
			"CUP_H_FR_Headset",
			"CUP_H_FR_PRR_BoonieWDL",
			"CUP_H_GER_Boonie_Flecktarn",
			"CUP_H_GER_Boonie_desert",

			"CUP_H_Navy_CrewHelmet_Blue",
			"CUP_H_Navy_CrewHelmet_Brown",
			"CUP_H_Navy_CrewHelmet_Green",
			"CUP_H_Navy_CrewHelmet_Red",
			"CUP_H_Navy_CrewHelmet_Violet",
			"CUP_H_Navy_CrewHelmet_White",
			"CUP_H_Navy_CrewHelmet_Yellow",
			"CUP_H_PMC_Cap_Grey",
			"CUP_H_PMC_Cap_PRR_Grey",
			"CUP_H_PMC_Cap_PRR_Tan",
			"CUP_H_PMC_Cap_Tan",
			"CUP_H_PMC_EP_Headset",
			"CUP_H_PMC_PRR_Headset",
			"CUP_H_RACS_Beret_Blue",
			"CUP_H_RACS_Helmet_DPAT",
			"CUP_H_RACS_Helmet_Des",
			"CUP_H_RACS_Helmet_Goggles_DPAT",
			"CUP_H_RACS_Helmet_Goggles_Des",
			"CUP_H_RACS_Helmet_Headset_DPAT",
			"CUP_H_RACS_Helmet_Headset_Des",
			"CUP_H_SLA_BeenieGreen",
			"CUP_H_SLA_Beret",
			"CUP_H_SLA_Boonie",
			"CUP_H_SLA_Helmet",
			"CUP_H_SLA_OfficerCap",
			"CUP_H_SLA_Pilot_Helmet",
			"CUP_H_SLA_SLCap",
			"CUP_H_SLA_TankerHelmet",

			"CUP_H_TK_Beret",
			"CUP_H_TK_Helmet",
			"CUP_H_TK_Lungee",
			"CUP_H_TK_PilotHelmet",
			"CUP_H_TK_TankerHelmet",
			"CUP_H_USMC_Crew_Helmet",
			"CUP_H_USMC_Goggles_HelmetWDL",
			"CUP_H_USMC_HeadSet_GoggleW_HelmetWDL",
			"CUP_H_USMC_HeadSet_HelmetWDL",
			"CUP_H_USMC_HelmetWDL",
			"CUP_H_USMC_Helmet_Pilot",
			"CUP_H_USMC_Officer_Cap"
			///"CUP_H_SLA_BeretRed",
		};
	};

	class CUPBackpacks
	{
		name = "CUPBackpacks";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
		items[] =
		{

		};
	};


	class CUPVests
	{
		name = "CUP Vests";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"CUP_V_BAF_Osprey_Mk2_DDPM_Grenadier",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Medic",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Officer",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Sapper",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Scout",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Soldier1",
			"CUP_V_BAF_Osprey_Mk2_DDPM_Soldier2",
			"CUP_V_BAF_Osprey_Mk2_DPM_Grenadier",
			"CUP_V_BAF_Osprey_Mk2_DPM_Medic",
			"CUP_V_BAF_Osprey_Mk2_DPM_Officer",
			"CUP_V_BAF_Osprey_Mk2_DPM_Sapper",
			"CUP_V_BAF_Osprey_Mk2_DPM_Scout",
			"CUP_V_BAF_Osprey_Mk2_DPM_Soldier1",
			"CUP_V_BAF_Osprey_Mk2_DPM_Soldier2",
			"CUP_V_BAF_Osprey_Mk4_MTP_Grenadier",
			"CUP_V_BAF_Osprey_Mk4_MTP_MachineGunner",
			"CUP_V_BAF_Osprey_Mk4_MTP_Rifleman",
			"CUP_V_BAF_Osprey_Mk4_MTP_SquadLeader",
			"CUP_V_B_GER_Carrier_Rig",
			"CUP_V_B_GER_Carrier_Rig_2",
			"CUP_V_B_GER_Carrier_Vest",
			"CUP_V_B_GER_Carrier_Vest_2",
			"CUP_V_B_GER_Carrier_Vest_3",
			"CUP_V_B_GER_Vest_1",
			"CUP_V_B_GER_Vest_2",
			"CUP_V_B_LHDVest_Blue",
			"CUP_V_B_LHDVest_Brown",
			"CUP_V_B_LHDVest_Green",
			"CUP_V_B_LHDVest_Red",
			"CUP_V_B_LHDVest_Violet",
			"CUP_V_B_LHDVest_White",
			"CUP_V_B_LHDVest_Yellow",
			"CUP_V_B_MTV",
			"CUP_V_B_MTV_LegPouch",
			"CUP_V_B_MTV_MG",
			"CUP_V_B_MTV_Marksman",
			"CUP_V_B_MTV_Mine",
			"CUP_V_B_MTV_Patrol",
			"CUP_V_B_MTV_PistolBlack",
			"CUP_V_B_MTV_Pouches",
			"CUP_V_B_MTV_TL",
			"CUP_V_B_MTV_noCB",
			"CUP_V_B_PilotVest",
			"CUP_V_B_RRV_DA1",
			"CUP_V_B_RRV_DA2",
			"CUP_V_B_RRV_Light",
			"CUP_V_B_RRV_MG",
			"CUP_V_B_RRV_Medic",
			"CUP_V_B_RRV_Officer",
			"CUP_V_B_RRV_Scout",
			"CUP_V_B_RRV_Scout2",
			"CUP_V_B_RRV_Scout3",
			"CUP_V_B_RRV_TL",
			"CUP_V_I_Carrier_Belt",
			"CUP_V_I_Guerilla_Jacket",
			"CUP_V_I_RACS_Carrier_Vest",
			"CUP_V_I_RACS_Carrier_Vest_2",
			"CUP_V_I_RACS_Carrier_Vest_3"
		};
	};